### DISCUSSION TITLE
Fetch container IP address of some service which has started and assign it to deployment env var of another service

### DISCUSSION THREAD

**Discussion by vlistratenko** [devspace-sh/devspace#1488] [Q&A]
Hello everyone,

Please, help with solving my issue.

I have a deployment as follows:

```
  - name: portfoliomanagement
    helm:
      componentChart: true
      values:
        containers:
          - image: ${service_image}
            env:
              - name: VAULT_ADDR
                value: ${vault_addr}
              - name: VAULT_TOKEN
                value:  ${vault_token}
            name: portfoliomanagement                       
        service:
          ports:
            - port: 80
```
My portfoliomanagement service needs to talk to Vault which is described and deployed in same devspace.yaml file.

The issue is that I need somehow to read IP address of deployed Vault service and assign it to ${vault_addr} env var of deployment.

I've tried different approaches but nothing worked. I'm able to fetch the IP address but not to properly assign to env var.

Please, share some ideas. Thanks in advance.
