### DISCUSSION TITLE
Is there a way to prevent a hook from running if the build step fails?

### DISCUSSION THREAD

**Discussion by uncvrd** [devspace-sh/devspace#1668] [Q&A]
Hi! I have a hook that I need to run after the build step, but before deploying. As a result I've defined a `hook` that looks like this:

```
hooks:
  - command: MY_COMMAND
    when:
      before:
        deployments: my-deployment
```

This works excellent, however, my build step sometimes fails and I'd like to prevent my `hook` from running if the build step fails. Is this possible? I would assume so since the deployment step doesn't run if the build fails. What can I do?

For some context, my `hook` runs a database migration before deployment so having a migration that runs after a failed build causes some small problems. Thanks for any insight!

**Comment by LukasGentele** [comment]
Are you using custom build commands? Does your build command return an exit code != 0 if it fails?

**Reply by uncvrd** [reply]
@LukasGentele hi! Yes I have a custom build command that looks like this:

```
build:
  custom:
    command: ./scripts/build-image.sh
    imageFlag: "-i"
    onChange:
      - app/analytics/src
    args:
      - -a
      - ${GOOGLE_SERVICE_ACCOUNT}
      - -p
      - ${GOOGLE_PROJECT_ID}
      - -s
      - app/analytics/src
```

And then in my build script:

```
#! /bin/bash

account=''
build_target=''
image=''
project=''
source=''

echo "-----Building Image-----"

while getopts 'a:i:p:s:t:' flag;
do
    case "${flag}" in
        a) account="${OPTARG}" ;;
        i) image="${OPTARG}" ;;
        p) project="${OPTARG}" ;;
        s) source="${OPTARG}" ;;
        t) build_target="${OPTARG}" ;;
    esac
done

gcloud builds submit "${source}" \
--substitutions=_IMAGE_NAME="${image}",_IMAGE_TARGET="${build_target}"

echo "-----Finished Building-----"

exit $?
```

...now that I'm looking at this (and im still a novice at scripting), but my understanding is that `exit $?` returns the code of the last command that was run, so with that logic, it's probably returning the status from the `echo` instead of the `gcloud` step which I wanted to return the error code from....let me try that out because maybe that's where the issue is! 🤔
