### DISCUSSION TITLE
Docker compose like env_file

### DISCUSSION THREAD

**Discussion by petkostas** [devspace-sh/devspace#1794] [Q&A]
We are slowly trying to move to devspace from docker-compose in a high-paced environment. Although transitioning most of the services from docker-compose files to devspace is easy, I encounter a problem, that is the lack (or my blindness) of `env_file` like configuration of services.
To be more precise, our stack consists of several services using the same framework, which renders the usage of separate env files for local development a necessity, as most framework-related variables use the same naming and require the use of separate env files to work properly. Is there something similar in dev space? I see support for single `.env` files, but that means that we need to rename every single variable we use (and there are many...)

**Comment by LukasGentele** [comment]
To clarify: If you have a `devspace.yaml` with 2 deployments, you want to specify 1 or more files for each of these deployments to auto-add environment variables from these files to the containers within the respective deployment?

**Reply by petkostas** [reply]
Yes correct!

**Reply by petkostas** [reply]
To be more clear, taking the official Django example, this is what I would be looking for:

```
deployments:
- name: foo
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/foo
        env_file:
        - configs/env/foo.env
      service:
        ports:
        - port: 8000
- name: bar                                      
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/bar
        env_file:
        - configs/env/bar.env
      service:
        ports:
        - port: 8001

**Reply by rafaeljusto** [reply]
Hey @petkostas , did you find a solution to this problem? I'm looking for the same feature. 🙂 

EDIT: Never mind, we found a good approach to solve this issue. I've posted it as a new discussion.

**Comment by rafaeljusto** [comment]
One approach we found useful was using [expressions](https://www.devspace.sh/docs/configuration/expressions):
```yaml
deployments:
- name: foo
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/foo
        env: $(cat common.env)
      service:
        ports:
        - port: 8000
- name: bar                                      
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/bar
        env: $(cat common.env)
      service:
        ports:
        - port: 8001
```

And `common.env` file would have the format:
```yaml
- name: "variable1"
  value: "value1"
- name: "variable2"
  value: "value2"
```

**Reply by lizardruss** [reply]
Glad you found a solution! One other approach is to create config map from your `.env` file, and using `envFrom` to load them into your container:

Command to create / update the config map during a `deploy` pipeline
```shell
kubectl apply configmap common-env --from-env-file=common.env
```

Reference it from your deployment in `devspace.yaml`
```yaml
deployments:
- name: foo
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/foo
        envFrom:
        - configMapRef:
            name: common-env
      service:
        ports:
        - port: 8000
```

In this case, the `common.env` would have the usual .env format:
```env
variable1=value1
variable2=value2
```

Depending on how you deploy your application, this approach could be more similar to that environment. Both are valid approaches, just wanted to add another solution.
