### DISCUSSION TITLE
Override `image` from component chart values loaded using `valuesFiles`

### DISCUSSION THREAD

**Discussion by hariprasadiit** [devspace-sh/devspace#2070] [Q&A]
Hello,

I've component chart values defined in separate yaml file which are used for production. I use devspace for development and testing. In dev env, docker registry is different but all the other component chart values would remain same. 

I would like to use component chart values file and deploy using componentChart option and only replace `image` with with different registry which is used in devspace to push built images.

I've tried profile's merge, replace and patches but nothing is working.

deployments section
```yaml
deployments:
  - name: server
    namespace: vms-dev
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      componentChart: true
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      valuesFiles: [ "./vms/server/chart-values.yaml" ]
```

profiles section
```yaml
  - name: dev
    activation:
      - vars:
          ENV: dev
    patches:
      - op: replace
        path: deployments.name=server.helm.values.containers[0].image
        value: image(server):tag(server)
```

Any help would be appreciated.

Thank you
