### DISCUSSION TITLE
Is it possible to use envFrom in custom charts like in component charts?

### DISCUSSION THREAD

**Discussion by pablorsk** [devspace-sh/devspace#2377] [Q&A]
How can I add something like

```yaml
envFrom:
  - secretRef:
      name: my-secret
      optional: true
```

to

```yaml
helm:
  chart:
    name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 17.0.5

```
