### DISCUSSION TITLE
Port Forwarding for third party helm chart

### DISCUSSION THREAD

**Discussion by ManAnRuck** [devspace-sh/devspace#2627] [Q&A] [answered]
Hey i want to try port forward grafana from the helm cart kube-prometheus-stack but i can’t open port 3000. It’s always no host. 

When i run a kubectl port-forward `kubectl port-forward -n MY_NAMESPACE $(kubectl get pods -n MY_NAMESPACE -l app.kubernetes.io/name=grafana -o jsonpath='{.items[0].metadata.name}') 3000:3000` it works. (demo app ports works also)

I use docker desktop (everithing latest version) and have the following devspace.yaml:

devspace.yaml

```yaml
version: v2beta1
name: development

dependencies:
  prometheus:
    path: devspace-prometheus.yaml
```

devspace-prometheus.yaml
```yaml
version: v2beta1
name: prometheus

deployments:
  prometheus:
    helm:
      chart:
        name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
dev:
  grafana:
    labelSelector:
      app.kubernetes.io/name: grafana
    ports:
      - port: '3000:3000'
    open:
      - url: http://localhost:3000/
```

**Comment by ManAnRuck** [comment, marked as answer]
`pipeline: dev` was missing 👍 

```
version: v2beta1
name: development

dependencies:
  prometheus:
    path: devspace-prometheus.yaml
    pipeline: dev
```
