### DISCUSSION TITLE
How to order deployments in v6?

### DISCUSSION THREAD

**Discussion by rafaeljusto** [devspace-sh/devspace#2880] [Q&A] [answered]
Hi,

Checking the [v5 documentation](https://www.devspace.sh/docs/5.x/configuration/deployments/basics) I can see that we use an array to guarantee the order of execution of the deployments.

https://github.com/devspace-sh/devspace/blob/04e45e7b84b3d647e5baedd4206c7116506e27cd/pkg/devspace/config/versions/latest/schema.go#L48

<img width="981" alt="image" src="https://github.com/user-attachments/assets/d90f2b74-4efe-4613-85db-c2adbd41eacd">

There was even a [concurrent flag](https://github.com/devspace-sh/devspace/pull/1884) added to allow running deployments in parallel or not.

For v6, the `Deployments` attribute was modified to a map, and Go maps are unordered by definition:
https://github.com/devspace-sh/devspace/blob/bed0daecfae22fd18c7491f329733891c21f51ea/pkg/devspace/config/versions/latest/schema.go#L69

The documentation for v6 doesn't mention anything related to ordering anymore, and the `Concurrent` feature was also removed.

How do I order the deployments in the latest version?

Thanks!

**Comment by rafaeljusto** [comment, marked as answer]
I found a way to enforce the order using init containers. It's useful when you have an HTTP interface available to check the status of the other deployment.

```yaml
deployments:
  app1:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: app1:1.2.3
        service:
          name: app1
          ports:
            - port: 80

  app2:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        initContainers:
          - name: wait-for-app1
            image: curlimages/curl:8.9.1
            command:
              - sh
            args:
              - -c
              - |
                while true; do
                  curl -sSf http://app1 && break
                  sleep 5
                done
        containers:
          - image: app2:1.2.3
```
