### ISSUE TITLE
Import and merging devspace configs

### ISSUE THREAD

**Issue by Co0ker** [devspace-sh/devspace#1067]
**Is your feature request related to a problem?**
We have many repositories with a unique devspace configuration.
I want to have a centralized template with a basic configuration (variables, commands).
Which may be related to other projects.

**Which solution do you suggest?**
Add Ability import and merging configuration from another repository

/kind feature

**Comment by FabianKramm** [comment]
@Co0ker thanks for opening this issue! Yes that sounds like a helpful feature. Since we support profile inheritance now, maybe we could allow loading base profiles from another file (or url?) that is applying the common configuration to the current devspace.yaml. The advantage of this is that we don't need any new concepts or config sections and it is rather easily implemented, but the disadvantage would be that it is not possible to apply a basic configuration to a non profile execution. What do you think about this?

**Comment by Co0ker** [comment]
Hi @FabianKramm!
Thanks for the quick response.

Basic global config - great idea idea!

**Comment by LukasGentele** [comment]
This is going to make config loading more complex. I see that this could be valuable but we need to make sure that we define a clear structure for this first.

After a discussion with @FabianKramm, I think the best solution is to integrate this into profiles because they already have the `parent` option which (so far) is only a reference (string) to another profile name. We could make an object out of this and allow git references as well. Additionally, we could add the option `default: true|false` for profiles which would allow to apply them without having to specify a profile.

This would be an example:
```yaml
profiles:
- name: default
  default: true                    # Apply this by default if no other profile is in use
  parent:
    name: my-profile          # Profile name (just as right now)
    source:                          # If this is not defined, we would assume the current devspace.yaml
      git: https://github.com/my-api-server
      branch: stable
```

If `source` is not defined, the behavior of `parent` would be as it is right now, just setting a parent from the other profiles defined in this devspace.yaml. If source is defined, it would load the file from the repository. The `source` option could follow the same syntax and logic as for dependencies: https://devspace.sh/cli/docs/configuration/dependencies/basics

@Co0ker, @FabianKramm, @ anyone else? How does that sound?
