### ISSUE TITLE
Better entrypoint override for interactive mode

### ISSUE THREAD

**Issue by ralfthewise** [devspace-sh/devspace#1122]
**Is your feature request related to a problem?**
It's related to slow redeployments around interactive mode.

**Which solution do you suggest?**
When running `devspace dev -i` the entrypoint override could be something like this:

```
      interactive:
        images:
          - name: frontend
            entrypoint:
              - sh
            cmd:
              - -c
              - "trap 'exit 1' TERM; sleep 999999999 & wait"
```

**Which alternative solutions exist?**
Manually provide the interactive config I pasted in the previous section.

**Additional context**
Doing `sleep 999999999` as the entrypoint takes a long time for the pod to terminate, because `sleep` doesn't handle `SIGTERM` - [https://superuser.com/a/1299463/157978](https://superuser.com/a/1299463/157978)

As is I just wait 10+ seconds for the pod to terminate before the new one is launched:

```
$ kubectl get all
NAME                            READY   STATUS        RESTARTS   AGE
pod/frontend-6c99b95f86-lmhmj   1/1     Terminating   0          2m2s
...
```

I'm happy to take a whack at this myself if you want, just wasn't sure if it might a quick fix for someone more familiar with the code (assuming it's a change worth adding).

/kind feature
