### ISSUE TITLE
configMap in dev mode

### ISSUE THREAD

**Issue by wansiedler** [devspace-sh/devspace#1158]
Hello, how can I mount configMap in dev mode?
This volumes section in deployments doesnt work in `devspace dev` mode =(

```
deployments:
- name: cryptoman10
  namespace: cryptoman
  helm:
    componentChart: true
    values:
      volumes:
      - name: my-config
        configMap:
          name: my-config
      containers:
      - image: eu.gcr.io/my-projectjwmt7xk/my-repositary/cryptoman
      service:
        ports:
        - port: 8000
```
