### ISSUE TITLE
Failed registering request: Session BUG!!!

### ISSUE THREAD

**Issue by PuppetA17** [devspace-sh/devspace#1216]
**What happened?**

## Development Mode ERROR!!! Display failed registering request: Session xxx

* devspace.yaml

```
version: v1beta9
dev:
  ports:
  - labelSelector:
      app: api
    forward:
    - port: 8080
      remotePort: 80
  logs:
    disabled: true
```

* Use the following command:
  `devspace dev`
* display MSG

```
[done] √ Port forwarding started on 8080:80                            
                                             
#########################################################
[info]   DevSpace UI available at: http://localhost:8090
#########################################################

[done] √ Sync and port-forwarding services are running (Press Ctrl+C to abort services)
00000000-0000-0000-0000-000000000000; failed registering request: Session 00000000-0000-0000-0000-000000000000 already exists
```

**What did you expect to happen instead?**
Don't display failed registering request: Session xxx

**How can we reproduce the bug?** (as minimally and precisely as possible)

**Local Environment:**

* DevSpace Version: 5.0.3
* Operating System: mac
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: other
* Kubernetes Version: v1.18.0

**Anything else we need to know?**

/kind bug
