### ISSUE TITLE
Parallel build leads to duplicate builds of the same image

### ISSUE THREAD

**Issue by ComaVN** [devspace-sh/devspace#1262]
**What happened?**
When running `devspace build` on a project with multiple images, created from the same `Dockerfile`, these images are built twice, without using each other's cached docker image layers.

**What did you expect to happen instead?**
I expect the docker build cache to be used so build times stay low, we don't unnecessarily burden resources needed during build, etc.

**How can we reproduce the bug?** (as minimally and precisely as possible)
[https://github.com/ComaVN/devspace-parallel-build](https://github.com/ComaVN/devspace-parallel-build) (See the readme)

TL;DR: when running `devspace dev`, the 2 containers return different results, because their randomly generated file is different. When running `devspace dev --build-sequential`, the containers return the same result, because they use the same image manifest/layers.

**Local Environment:**

* DevSpace Version: 5.5.0
* Operating System: Ubuntu 20.04.1 LTS
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Cloud Provider: DevSpace Cloud
* Kubernetes Version: v1.19.4 Client & Server

**Anything else we need to know?**
My actual usecase is a bit more complex: my Dockerfile is multistage, where stage B depends on stage A, container 1 uses stage A and container 2 uses stage B. The behaviour is the same: stage A is built twice.

If it is not feasible to actually fix this (which I can understand) it would be very acceptable to be able to disable parallel builds in `devspace.yaml`

/kind bug

**Comment by FabianKramm** [comment]
@ComaVN thanks for reporting this issue! Yes the problem is that ${DEVSPACE_RANDOM} will resolve to the same string in both cases. This will be fixed with the new version v5.6.0 which we release soon that introduces '#' instead of ${DEVSPACE_RANDOM}:
```yaml

version: v1beta9
images:
  foo:
    dockerfile: Dockerfile
    image: dockerregistry.example.com/comavn-devspace-parallel-build-foo
    tags:
      - dev-${DEVSPACE_USERNAME}-#####
    build:
      docker:
        useBuildKit: true
        options:
          buildArgs:
            timestamp: ${DEVSPACE_TIMESTAMP}
  bar:
    dockerfile: Dockerfile
    image: dockerregistry.example.com/comavn-devspace-parallel-build-bar
    tags:
      - dev-${DEVSPACE_USERNAME}-#####
    build:
      docker:
        useBuildKit: true
        options:
          buildArgs:
            timestamp: ${DEVSPACE_TIMESTAMP}
deployments:
  - name: dev
    kubectl:
      replaceImageTags: true
      manifests:
        - deployment.yaml
```
