### ISSUE TITLE
Adding dev.sync.imageName breaks sync destination pod

### ISSUE THREAD

**Issue by noizwaves** [devspace-sh/devspace#1353]
**What happened?**
When adding the `dev.sync.imageName` configuration to gain [preferred sync over rebuild behavior](https://devspace.sh/cli/docs/configuration/images/prefer-sync-over-rebuild#example-prefer-sync-over-rebuild) to an orchestration where **one image** is deployed to **many pods** (in this case, the `app` image is used to run 3 containers across 2 pods), `devspace` selects the wrong destination pod as the sync target.

The deployment manifest looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    module: hi-app
    service: hi-worker
  name: hi-worker
spec:
  selector:
    matchLabels:
      service: hi-worker
  template:
    metadata:
      labels:
        module: hi-app
        service: hi-worker
    spec:
      containers:
        - name: hi-worker
          args:
            - bin/sidekiq
          command:
            - /bin/sh
            - -c
          image: 1234567890.dkr.ecr.us-west-2.amazonaws.com/cloud-dev-staging/hi-image
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    module: hi-app
    service: hi-web
  name: hi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hi-web
  template:
    metadata:
      labels:
        module: hi-app
        service: hi-web
    spec:
      containers:
        - name: hi-web
          command:
            - bundle
            - exec
            - puma
          image: 1234567890.dkr.ecr.us-west-2.amazonaws.com/cloud-dev-staging/hi-image
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
        - name: hi-webpack
          command:
            - yarn
            - start
          image: 1234567890.dkr.ecr.us-west-2.amazonaws.com/cloud-dev-staging/hi-image
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
```

**Before** making the changes, the contents of `devspace.yaml`:

```
images:
  app:
    image: 1234567890.dkr.ecr.us-west-2.amazonaws.com/cloud-dev-staging/hi-image
    dockerfile: ./Dockerfile.dev
    preferSyncOverRebuild: true
dev:
  sync:
    - labelSelector:
        service: hi-web
      containerName: hi-web
      excludePaths:
        - ...
    - labelSelector:
        service: hi-web
      containerName: hi-webpack
      excludePaths:
        - ...
```

**Before** making the changes, the output of `devspace dev` reveals:

```
# devspace dev
[info]   Using namespace 'adam-neumann'
...
[0:sync] Start syncing
[done] √ Sync started on /Users/adam.neumann/workspace/hi <-> . (Pod: adam-neumann/hi-web-656bb7f578-mvmxc)
[1:sync] Start syncing
[done] √ Sync started on /Users/adam.neumann/workspace/hi <-> . (Pod: adam-neumann/hi-web-656bb7f578-mvmxc)
[done] √ Sync and port-forwarding services are running (Press Ctrl+C to abort services)
```

**After** making the changes, the contents of `devspace.yaml`:

```
images:
  app:
    image: 1234567890.dkr.ecr.us-west-2.amazonaws.com/cloud-dev-staging/hi-image
    dockerfile: ./Dockerfile.dev
    preferSyncOverRebuild: true
dev:
  sync:
    - labelSelector:
        service: hi-web
      imageName: app
      containerName: hi-web
      excludePaths:
        - ...
    - labelSelector:
        service: hi-web
      imageName: app
      containerName: hi-webpack
      excludePaths:
        - ...
```

**After** making the changes, the output of `devspace dev` reveals syncing to `adam-neumann/hi-worker-5fb566c78-nxcp5` now instead of `adam-neumann/hi-web-656bb7f578-mvmxc`:

```
$ devspace dev
[info]   Using namespace 'adam-neumann'
...
[0:sync:app] Start syncing
[done] √ Sync started on /Users/adam.neumann/workspace/hi <-> . (Pod: adam-neumann/hi-worker-5fb566c78-nxcp5)
[1:sync:app] Start syncing
[done] √ Sync started on /Users/adam.neumann/workspace/hi <-> . (Pod: adam-neumann/hi-worker-5fb566c78-nxcp5)
[done] √ Sync and port-forwarding services are running (Press Ctrl+C to abort services)
```

**What did you expect to happen instead?**

I was expecting the destination pod selected for file syncing to remain as `adam-neumann/hi-web-656bb7f578-mvmxc`.

**How can we reproduce the bug?** (as minimally and precisely as possible)

The information above should be enough to reproduce it.

**Local Environment:**

* DevSpace Version: `devspace version 5.9.1`
* Operating System:mac
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Cloud Provider: aws
* Kubernetes Version: 1.16

**Anything else we need to know?**
