### ISSUE TITLE
Component Chart Deployment ServiceAccount creation and assignment

### ISSUE THREAD

**Issue by kollerdroid** [devspace-sh/devspace#1427]
Deployed Pod always assigned to default ServiceAccount. RBAC features are not really applicable (eg.  ServiceAccount binding in case of Vault secret injections).

I would like to follow Helm best practices for [ServiceAccount configuration](https://helm.sh/docs/chart_best_practices/rbac/#yaml-configuration).

How can I create a ServiceAccount for a deployment created by a Component Chart?

If it is not possible to create a ServiceAccount with Component Chart, can I just assign an existing SA to a Deployment?

> As I see in ***deployment.yaml*** template it could be possible:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/ac33ebcf-0f4d-404c-9769-8da9b053f740/e8607984-278d-4ce0-9a2c-4c7190efd821)

Can I somehow define this value? eg. in ***devspace.yaml***:

```
deployments:
  - name: <name>
    helm:
      componentChart: true
      values:
        containers:
        # eg. somewhere here?
```

/kind feature

**Comment by FabianKramm** [comment]
@kollerdroid thanks for creating this issue! Yes, currently it is not possible to create a service account via the component chart, however you could either do this via a separate deployment (just a single serviceaccount.yaml) and assign this serviceaccount to the deployment:

```yaml
deployments:
  - name: <name>
    helm:
      componentChart: true
      values:
        serviceAccountName: my-service-account
        containers:
          ...
```
