### ISSUE TITLE
Devspace deploy command in shell script execute cannot correctly find the pod status

### ISSUE THREAD

**Issue by xwen-winnie** [devspace-sh/devspace#1461]
**What happened?**
The devspace deploy --debug xxx.yaml command run in the script cannot correctly determine the status of the pod and exit.

**What did you expect to happen instead?**

When the deployed task pod is finally running, it has coded 0 and exits normally.
When the deployed task CrashLoopBackOff found that the pod was abnormal and exited with code 1.
**How can we reproduce the bug?** (as minimally and precisely as possible)

1. First prepare a k8s deployment yaml file, a devspace yaml file and a script file.(Below is my test file)

busybox-deployment.yaml
(You can see that the final deployment will 'CrashLoopBackOff' when the field after the while in the last line of busybox-deployment.yaml is 'false', will 'Running' when is is 'true')

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.33
        args: 
        - "/bin/sh"
        - "-c"
        - "while false; do echo $(date); sleep 1; done"
```

test-devspace.yaml

```
version: v1beta10
deployments:
- name: "busybox"      
  kubectl:                  
    manifests:
    - busybox-deployment.yaml
```

[test.sh](http://test.sh)

```
#!/bin/bash
set -ex

devspace deploy --debug --verbose-dependencies --wait=true --timeout=3 --config test-devspace.yaml
```

1. sh [test.sh](http://test.sh)
2. You may find that the script will eventually exit normally. This will not happen 100%, but it will always appear after many attempts.
   success:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/206490ec-2bfc-4ce7-a2a5-19af68f81a8d/ceced3fb-c953-48e4-817c-022517ec101c)

failed:

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/52c12eda-0545-43dc-82bc-66da0843873e/e5b3b20a-5c19-4e4b-8ea1-5cb01cb670f2)

1. Please delete the deployment resource of the last deployment before repeating 2) each time (k delete deploy busybox-deployment). If you execute the next time without deleting it after one deployment, the next time the result will must be an error exit of devspace
2. If the devspace deploy… command is executed without a script, the pod error will be found and exit every time as expected.

**Local Environment:**

* DevSpace Version:  v5.14.0
* Operating System: mac
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Kubernetes Version:
  Client Version: [version.Info](http://version.Info){Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: [version.Info](http://version.Info){Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**

I also changed the devspace to v1beta9. I tested it and reproduced the above errors.

/kind bug

**Comment by FabianKramm** [comment]
@xwen-winnie thanks for creating this issue and the extra information! As far as I see it, this is a race condition as the container will be Running for a very short period of time and thus is actually expected behaviour as DevSpace will wait for a pod to be running and then exit. 

This example makes it more obvious:
```yaml
. For example take:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.33
        args: 
        - "/bin/sh"
        - "-c"
        - "sleep 10; exit 1"
```

With this you will encounter that behaviour every time, as the container will be running for 10s and then fail. DevSpace will always terminate successfully with this. There is no real solution to the problem except for telling DevSpace to not only wait until it is running, but also to wait for a certain amount of time after the pod is running, which we could think about and at least would solve cases like yours when the container basically fails directly after it was Running.
