### ISSUE TITLE
Named Minikube Cluster is not recognized as local Kubernetes cluster

### ISSUE THREAD

**Issue by johnnypea** [devspace-sh/devspace#1932]
I run vcluster in Minikube localy for testing purposes and I can't get local image building working.

Please, could you check my config? I'm not sure about "buildKit" and "docker" parts in images section.

```
vars:
  - name: REGISTRY
    value: "myapp.local" 

images:
  php:
    image: ${REGISTRY}/php
    dockerfile: api/Dockerfile
    context: api/
    build:
      buildKit: 
        inCluster: {}
        skipPush: true
      docker:
        options:
          target: symfony_php
          
deployments:
- name: app
  helm:
    componentChart: true
    values:
      containers:
      - name: php-container
        image: ${REGISTRY}/php
```

Tags are the same but it doesn't use local image, why?

```
[php] Info: Building image 'myapp.local/php:WdljxgD' with engine 'buildkit'
```

```
[info]   Execute hook 'wait for selector app.kubernetes.io/component=app' at after:deploy:app
[warn]   Pod intraspace/app-0 has critical status: ErrImagePull. DevSpace will continue waiting, but this operation might timeout
[fatal]  error deploying: in hook 'wait for selector app.kubernetes.io/component=app': timed out waiting for the condition
```

```
  - image: myapp.local/php:WdljxgD
    imageID: ""
    lastState: {}
    name: php-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'rpc error: code = Unknown desc = Error response from daemon: Get
          "https://myapp.local/v2/": dial tcp: lookup myapp.local: Temporary failure
          in name resolution'
        reason: ErrImagePull
```

It looks like the images are build with local docker daemon on my host not in the actual cluster.

```
❯ docker images
REPOSITORY                TAG         IMAGE ID       CREATED             SIZE
myapp.local/php           WdljxgD     656d1af96fb0   14 minutes ago      191MB
```

This config works with Minikube without BuildKit and vcluster.

Thank you. 🙏

**Comment by pratikjagrut** [comment]
@johnnypea Thank you for the issue. We'll look into this.

**Comment by pratikjagrut** [comment]
We made a mistake in doc. I think the correct config should be like below:
```
 php:
    image: ${REGISTRY}/php
    dockerfile: api/Dockerfile
    context: api/
    build:
      buildKit: 
        inCluster: {}
        skipPush: true
        options:
          target: symfony_php
```

Could you please try this out?

**Comment by FabianKramm** [comment]
@johnnypea maybe try to use `imagePullPolicy: Never` as this might help

**Comment by johnnypea** [comment]
@FabianKramm didn't help :(

```
  - image: myapp.local/php:fMyzTrj
    imageID: ""
    lastState: {}
    name: php-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Container image "myapp.local/php:fMyzTrj" is not present
          with pull policy of Never
        reason: ErrImageNeverPull
```
