### ISSUE TITLE
Spurious redeploys for charts not in current namespace

### ISSUE THREAD

**Issue by SohumB** [devspace-sh/devspace#1933]
If you have a helm deployment that sets a namespace different from the namespace used on the command line,

```
deployments:
- name: keda
  namespace: keda
  helm:
    chart:
      name: keda
      version: "2.6.2"
      repo: "https://kedacore.github.io/charts"
```

`devspace` will always redeploy this release, regardless of whether it needs to be.

I've tracked the issue down to here: [https://github.com/loft-sh/devspace/blob/d6091ae88e16cc251541bb962335d90f93610d8c/pkg/devspace/deploy/deployer/helm/deploy.go#L89-L100](https://github.com/loft-sh/devspace/blob/d6091ae88e16cc251541bb962335d90f93610d8c/pkg/devspace/deploy/deployer/helm/deploy.go#L89-L100)

The call to `Helm.ListReleases` uses the current context, and therefore only looks within the currently set namespace in that context.

**Local Environment:**

* DevSpace Version: 5.18.4
* Operating System: linux
* ARCH of the OS: AMD64

**Kubernetes Cluster:**

* Distro: minikube
* Kubernetes Version: 1.23.1

/kind bug
