### ISSUE TITLE
vars in a profile not overriding the default vars

### ISSUE THREAD

**Issue by tobalsgithub** [devspace-sh/devspace#2262]
**What happened?**

If I try to override a `var` in a profile using the `merge` option, it does not work.

**What did you expect to happen instead?**
I would expect any `var` defined in a profile to override the default `var` section.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: bug
vars:
  VAR_1: 'value 1'

pipelines:
  build:
    run: |-
      echo $VAR_1

profiles:
- name: asdf
  merge:
    vars:
      VAR_1: 'value 2'
```

Then run `devspace print -p asdf`. You will see that `VAR_1` is set to `value 1`, whereas I would expect it to be set to `value 2`. This worked as expected in the beta version of v6, but stopped working when we upgraded to version 6.0.0 and still does not work on version 6.0.1.

**Local Environment:**

* DevSpace Version: devspace version 6.0.1
* Operating System: linux | mac (seeing on both linux and mac)
* ARCH of the OS: AMD64 | ARM64
  **Kubernetes Cluster:**  N/A
* Cloud Provider: N/A
* Kubernetes Version: N/A

**Anything else we need to know?**

/kind bug

**Comment by tobalsgithub** [comment]
fwiw, it doesn't look like `patch` or `replace` work for overriding `vars` either. 

```
version: v2beta1
name: bug
vars:
  VAR_1: 'value 1'

pipelines:
  build:
    run: |-
      echo $VAR_1   

profiles:
- name: asdf
  merge:
    vars:
      VAR_1: 'value 2'
- name: patch
  patches:
  - op: replace
    path: vars.VAR_1
    value: 'value 3'
- name: replace
  replace:
    vars:
      VAR_1: 'value 4'
```

**Comment by tobalsgithub** [comment]
Switching the profile to use `alwaysResolve: true` also doesn't seem to help. 

```
profiles:
- name: asdf
  merge:
    vars:
      VAR_1: 
        value: 'value 2'
        alwaysResolve: true
```

**Comment by tobalsgithub** [comment]
Variables that are ONLY defined in the profile section seem to show up correctly. So to me, this looks like the merge order got reversed from what I would expect, with default vars overriding profile vars, instead of the other way around.

**Comment by pablorsk** [comment]
Confirmed bug :lady_beetle: 

Temporal solution 

```
profiles:
- name: all
  activation:
    - vars:
        DEVSPACE_PROFILE:
  patches:
  merge:
    vars:
      APP_ENV: 'local'
- name: production
  merge:
    vars:
      APP_ENV: 'production'
 ```

And `APP_ENV` was removed from `vars` section.
