### ISSUE TITLE
Profile patches are not applied to helm values loaded with `$(cat values.yaml)`

### ISSUE THREAD

**Issue by hariprasadiit** [devspace-sh/devspace#2315]
**What happened?**
Profile patches are not applied if helm values are loaded from a file with `$(cat values.yaml)`. I have used this feature in v5 as values can't be patched if imported using `valuesFiles`.

**What did you expect to happen instead?**
Able to apply profiles patches to helm values

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. create component chart helm values file.
2. load values file using `$(cat values.yaml)`
3. try applying profile patches on it

My devspace.yaml:

```
version: v2beta1

deployments:
  server:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values: $(cat values.yaml)

profiles:
 - name: beta
    activation:
      - vars:
          ENV: beta
    patches:
      - op: replace
        path: deployments.server.helm.values.containers[0].image
        value: vizmo/server
```

**Local Environment:**

* DevSpace Version: v6.1.1
* Operating System: mac
* ARCH of the OS: AMD64

/kind bug
