### ISSUE TITLE
Docker targets when building image are ignored

### ISSUE THREAD

**Issue by alexissellier** [devspace-sh/devspace#2316]
**What happened?**
When building images, docker target are ignored

**What did you expect to happen instead?**

**How can we reproduce the bug?** (as minimally and precisely as possible)
Build two images with different target and you would see in the log that your Dockerfile instructions are executed, not only the one related to your target.

My devspace.yaml:

```
[...]
images:
  monolith:
    image: ${IMAGES_REG}/monolith:${DEVSPACE_GIT_COMMIT}
    dockerfile: devspace.Dockerfile
    target: monolith-dev
    buildArgs:
      PHP_IMAGE_BASE: stable
  assets:
    image: ${IMAGES_REG}/assets:${DEVSPACE_GIT_COMMIT}
    dockerfile: devspace.Dockerfile
    target: assets-dev
[...]
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System:  Linux and Mac
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
  local kind cluster

**Anything else we need to know?**

I've checked the code and the logs of my docker daemon and it saw that the `Version` field in the `types.ImageBuildOptions` (builder/docker/docker.go)  is not mentioned and thus defaulted to '1' which is not the buildkit builder.

When setting `Version` to `types.BuilderBuildKit`, my targets are taking into account and everything is right but no logs are displayed. The log lines seem to lie in the `Aux` variable of the `JSONMessage` as base64d string and I've not find any `auxCallback` to decode them

/kind bug
