### ISSUE TITLE
Backward compatibility issue - hooks for named sync from v1beta11 don't work with devspace v6

### ISSUE THREAD

**Issue by matskiv** [devspace-sh/devspace#2371]
**What happened?**
When using devspace v6 with a v1beta11 configuration some sync hooks are not executed.

**What did you expect to happen instead?**
I expected my hook to be executed after a named sync is finished.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Add a named sync and a hook from the example below to a devspace.yaml that uses `version: v1beta1` and run `devspace dev`.
The is the relevant part of my devspace.yaml:

```
version: v1beta1
# ...
dev:
  sync:
    - name: ok
      imageSelector: ${IMAGE}

hooks:
- events: ["after:initialSync:ok"]
  command: "echo TEST - OK"
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: linux
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: minikube
* Kubernetes Version: Client "v1.24.2"

**Anything else we need to know?**
This works as expected with devspace v5

/kind bug
