### ISSUE TITLE
passing an absolute path to kubectl manifest

### ISSUE THREAD

**Issue by agarwalarjun123** [devspace-sh/devspace#2379]
**Is your feature request related to a problem?**
my k8s manifests are not in the same directory as devspace.yaml.
**Which solution do you suggest?**
I need an option to give an absolute path to kubectl manifest directory.

/kind feature

**Comment by carlmontanari** [comment]
👋 @agarwalarjun123 

Unless I'm miss-understanding, this should "just work" ™️ -- you should be able to provide relative or absolute paths no problem. [here](https://github.com/loft-sh/devspace-example-python/tree/main/02-fastapi-tortoise) in the python devspace example we have a manifests dir, then in the `devspace.yaml` we refer to the manifests like:

```yaml
deployments:
    simple-project:
      kubectl:
        manifests:
          - manifests/deployment.yaml
          - manifests/ingress.yaml
          - manifests/svc.yaml
```

Let us know if thats not working. If it isn't please provide a minimum reproducible example so we can understand whats going on.
