### ISSUE TITLE
Command to start port-forwarding independently

### ISSUE THREAD

**Issue by igoooor** [devspace-sh/devspace#2391]
**Is your feature request related to a problem?**
Not a problem

**Which solution do you suggest?**
In the same way that we have `devspace sync` would it be possible to have something like `devspace port-forward` and `--skip-port-forwarding` ?

**Which alternative solutions exist?**
`devspace dev -skip-build --skip-push --skip-deploy`

Sorry if I overlooked the documentation and if such things already exist but I could not find it

**Comment by marklarr-gfm** [comment]
Hey there,

We're interested in this functionality as well. Our use case is that we are running `devspace deploy` inside of our CI process (a GitHub CI runner), and then we want to run some smoke tests against those deployments from the GitHub Runner. In order to run those smoke tests, the GitHub runner needs ports forwarded to the devspace deployments.

We're not using `devspace dev` in the GitHub runner because it runs indefinitely and requires a ctrl-c to stop it.

**Comment by lizardruss** [comment]
@marklarr-gfm I think something close to what you desire would be possible with a custom pipeline. I'll share an example to illustrate, but I may have misunderstood the use case:

**devspace.yaml**
```
version: v2beta1

deployments:
  app1:
    ... # details omitted
  app2:
    ... # details omitted

pipelines:
  e2e: |-
    # copied from the default pipeline, edit as needed
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all

    # start port-forwarding, file syncing etc
    start_dev --all
    
    # run your smoke tests from the GitHub runner
    make tests
    
    # stop port-forwarding, file syncing etc and exit
    stop_dev --all

dev:
  app1:
    imageSelector: ghcr.io/org/project/app1
    ports:
    - port: "8080:8080"
  app2:
    imageSelector: ghcr.io/org/project/app2
    ports:
    - port: "8181:8080"
```

You'd run this with:
```sh
> devspace run-pipeline e2e
```

`devspace dev` would work as it does normally.

This is a pseudo code example, but it's very similar to how we run the e2e tests for our commercial product. It assumes that you wouldn't need to deploy the `smoke-test-runner` pod and could use the runner to execute tests, but it could be adapted to also use a pod for running smoke tests too.

The main thing is that `start_dev` and `stop_dev` can be used to start / stop port forwarding as needed and run any commands you need while port forwarding is active.

**Comment by lizardruss** [comment]
@igoooor For your use case, I think a custom pipeline + dev configuration would do the trick for only starting port-forwarding. Here's an example:

**devspace.yaml**
```yaml
version: v2beta1

deployments:
  app1:
    ... # details omitted
  app2:
    ... # details omitted

pipelines:
  port-forward: |-
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all

    # Only start the dev sections for port-forwarding
    start_dev app1-pf app2-pf

dev:
  app1-pf:
    imageSelector: ghcr.io/org/project/app1
    ports:
    - port: "8080:8080"
  app2-pf:
    imageSelector: ghcr.io/org/project/app2
    ports:
    - port: "8181:8080"
```

Similarly you'd run:
```sh
devspace run-pipeline port-forward
```

I think `devspace sync` could be reproduced with a similar technique, but we kept it for backwards compatibility.

**Comment by marklarr-gfm** [comment]
@lizardruss thanks for the response. I gave `start_dev` / `stop_dev` a try, but I think the issue I am running into is specific to our project's setup. We have a monorepo with several apps, and we're using devspace `dependencies` to split those apps up into multiple devspace.yaml projects. I've put together a minimal example to show everything I've tried. `attempt1`, `attempt2`, attempt3`, and `attempt4` pipelines all hang indefinitely without a ctrl-c.

[10_02_2023.zip](https://github.com/devspace-sh/devspace/files/12785277/10_02_2023.zip)

**Comment by lizardruss** [comment]
@marklarr-gfm Thanks for the example. I see your case a little bit better now. My suggestion would be to only deploy the `foo` dependency and not attempt to start and stop dev for dependencies from the top level `devspace.yaml`. Instead, I would add a top level `dev` configuration that contains the port-forwarding needed for the tests to run.

Here's an example based on the zip files you sent:
**devspace.yaml**
```yaml
version: v2beta1
name: "10022023"

dependencies:
  foo:
    path: foo/devspace.yaml
    
pipelines:

  # other attempts omitted

  attempt5: |
    run_dependency_pipelines foo # --pipeline deploy (can define a custom one, just don't use start_dev in it)
    start_dev foo-tests
    echo "hello world"
    stop_dev foo-tests
dev:
  foo-tests:
    labelSelector:
      name: foo
    ports:
      - port: 5000
```

This does require the top level `foo-tests` config to have knowledge of the dependencies ports.. but since the test would need that information too, it seems reasonable.
