### ISSUE TITLE
devspace does not create namespace for dependency deployment

### ISSUE THREAD

**Issue by lusu007** [devspace-sh/devspace#2399]
**What happened?**
I declared a dependency in my `devspace.yaml` file with the namespace config option set. The namespace does not exist when starting the cluster. The deployment fails because the namespace isn't created.

**What did you expect to happen instead?**
Devspace should create this namespace automatically (see #605).

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: xxx-api

pipelines:
   dev:
    run: |-
      run_dependencies --all      
      create_deployments --all    
      start_dev app                

deployments:
  xxx-api:
    helm:
      chart:
        name: xxx-api
        repo: https://xxx.xxx.net/
        username: ${HELM_USERNAME}
        password: ${HELM_PASSWORD}
      valuesFiles: ["dev/values.yaml"]

dev:
  app:
    devImage: ghcr.io/lusu007/devspace-containers/typescript:18-alpine
    imageSelector: xxx.xxx.xxx:5005/xxx-api:nightly
    sync:
      - path: ./
        uploadExcludeFile: .dockerignore
    terminal:
      command: NPM_TOKEN=${NPM_TOKEN} ./devspace_start.sh
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - command: git
    ports:
      - port: "9229"
      - port: "3000"
    open:
      - url: http://localhost:3000
vars:
  HELM_PASSWORD:
    password: true
  NPM_TOKEN:
    question: "Please enter your NPM token:"
    password: true

dependencies:
  xxx-api:
    git: https://xxx.xxx/xx/xx/xxxx
    branch: dev
    pipeline: dev
    namespace: xxx-api
```

**Local Environment:**

* DevSpace Version: 6.1.1
* Operating System: Linux Ubuntu (WSL)
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: kind
* Kubernetes Version:  v1.25.3

**Anything else we need to know?**
