### ISSUE TITLE
Consider binding to localhost instead of 127.0.0.1

### ISSUE THREAD

**Issue by withinboredom** [devspace-sh/devspace#2409]
[https://github.com/loft-sh/devspace/blob/596b007df4b4d7cbaafb188ee48295d68ebcf599/pkg/devspace/server/port_forward.go#L94](https://github.com/loft-sh/devspace/blob/596b007df4b4d7cbaafb188ee48295d68ebcf599/pkg/devspace/server/port_forward.go#L94)

With the prevalence of ipv6-only networks growing (and allowing this to work in environments like WSL), can you please consider binding to `localhost` instead of a hardcoded ipv4 address?

**Comment by FabianKramm** [comment]
@withinboredom thanks for creating this issue! We have an option to override this with:
```
dev:
  my-dev:
     ports:
    - port: 8080
      bindAddress: "localhost"
```
