### ISSUE TITLE
devspace deploy fails in CI/CD-flow after upgrade to devspace 6.1

### ISSUE THREAD

**Issue by rosen91** [devspace-sh/devspace#2415]
**What happened?**
Recently updated our Gitlab CI/CD-flow to use devspace 6.1 instead of 4.x. Also updated devspace.yaml to use new syntax and v2beta1 so it sure might be an issue in my reconfiguration that causes this. But when deploying with `devspace deploy` it fails with:
`/root/.devspace/bin/helm: text file busy`

![](https://uploads.linear.app/0aab256f-61c4-44f4-9aff-15fe09c2026b/fcdc0772-fc0d-4a49-a33d-2fbe49b2e674/cfadaf89-9abd-461b-a515-2174fbb8d0d4)

This particaluar job has multiple deployments, database, redis, api etc, and it fails on different deployments every time. Asked in Slack and @FabianKramm thought it might be something to do with downloading helm binary and parallel deployments.

**What did you expect to happen instead?**
It would deploy successfully and move on to the other dependencies.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Don't really know.. It's a big project with multiple dependencies, devspace.yaml files and it's running in Gitlab CI/CD with the Kubernetes executor on GCP. I can give access to repository if needed.

My devspace.yaml:

```
version: v2beta1
images: ...
deployments: 
  api-gateway-search:
    kubectl:
      manifests:
        - search/
  api-gateway-config:
    kubectl:
      manifests:
        - config/
   api-gateway-database:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          ...
        volumes:
         ...
        service:
        ,,,
        
     more-services...
...
```

**CI/CD Environment:**

* DevSpace Version: \[use `devspace --version`\]
  image:
  name: devspacesh/devspace:6.1
* Operating System: windows | linux | mac
  Linux
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
* Cloud Provider: google | aws | azure | other
  Google
* Kubernetes Version: \[use `kubectl version`\]

**Anything else we need to know?**
