### ISSUE TITLE
Option to specify multiple existing PVCs

### ISSUE THREAD

**Issue by lusu007** [devspace-sh/devspace#2426]
**Is your feature request related to a problem?**
We are caching the `node_modules` and `~/.npm` directories in my organization to speed up devspace starts. At the moment we are mounting both directories in one PVC. But we want to mount the `~/.npm` directory to multiple pods to share this folder as a global cache, as intended by npm.
The issue is that devspace doesn't give me the option to specify multiple PVCs in the config.

**Which solution do you suggest?**
Let us specify multiple PVCs in `persistenceOptions.name` and the option to select a PVC in the `persistPaths object[]` per array entry.

**Which alternative solutions exist?**
n/a

**Additional context**
n/a

**Comment by alexandradragodan** [comment]
Hey, @lusu007 
Thank you for reporting this issue! 

My colleagues are looking for a workaround that would support your described issue! 
In the meantime, we're considering adding this feature. 

Will keep you posted!

**Comment by lusu007** [comment]
I found a workaround until this feature gets implemented. The workaround patches a `volume` and a `volumeMount` into the Devspace container by using Devspace's [pod patches](https://www.devspace.sh/docs/configuration/dev/modifications/patches) feature.

If the container already has a volume mounted the following snippet will work:
```yaml
patches:
  - op: add
    path: spec.volumes
    value:
      name: npm-cache
      hostPath:
        path: /var/local-path-provisioner/npm-cache
        type: DirectoryOrCreate
  - op: add
    path: spec.containers.name=app.volumeMounts
    value:
      name: npm-cache
      mountPath: /root/.npm
```

If the container has no volume mounted we need to change the snippet a little bit:
```yaml
patches:
  - op: add
    path: spec
    value:
      volumes:
        - name: npm-cache
          hostPath:
            path: /var/local-path-provisioner/npm-cache
            type: DirectoryOrCreate
  - op: add
    path: spec.containers.name=app
    value:
      volumeMounts:
        - name: npm-cache
          mountPath: /root/.npm
```

We are using kind as our development cluster. Using kind Pods will have the permission to create a directory in `/var/local-path-provisioner/`. The path will probably change when using another Kubernetes tool.
