### ISSUE TITLE
devspace build not working on WSL2

### ISSUE THREAD

**Issue by lee-aaron** [devspace-sh/devspace#2447]
**What happened?**
This runs fine on my MacOS but I can't seem to build devspace on WSL2. Getting the output below.

```
Ensuring image pull secret for registry: DESKTOP-R2R7EL6:5000...
Couldn't retrieve username for registry DESKTOP-R2R7EL6:5000 from docker store
Couldn't retrieve password for registry DESKTOP-R2R7EL6:5000 from docker store
local-registry: Starting Local Image Registry
local-registry: Port forwarding to local registry started on: 32424 -> 5000
Ensuring image pull secret for registry: DESKTOP-R2R7EL6:5000...
Couldn't retrieve username for registry DESKTOP-R2R7EL6:5000 from docker store
Couldn't retrieve password for registry DESKTOP-R2R7EL6:5000 from docker store
build:objectstorage Rebuild image localhost:32424/objectstorage: because it was not found in the local registry
build:objectstorage Building image 'localhost:32424/objectstorage:kcHuFXj' with engine 'docker'
build:objectstorage Execute docker cli command with: docker build --tag localhost:32424/objectstorage:kcHuFXj --file Dockerfile --platform=linux/amd64 -
#1 [internal] load remote build contextxt to Docker daemon  557.1kB
build:objectstorage #1 sha256:64d03271ddd574b62c0f129a578a5bec9fb8dcf391e2aab6da89449abad7fb1e
build:objectstorage #1 ERROR: invalid response status 403
build:objectstorage ------
build:objectstorage  > [internal] load remote build context:
build:objectstorage ------
build:objectstorage failed to read downloaded context: failed to load cache key: invalid response status 403
build_images: build images: error building image localhost:32424/objectstorage:kcHuFXj: error executing 'docker build --tag localhost:32424/objectstorage:kcHuFXj --file Dockerfile --platform=linux/amd64 -':
fatal exit status 1
```

**What did you expect to happen instead?**
Pretty much expect to be able to authenticate without coming across a 403 forbidden error. I should see building / deploying working fine.

**How can we reproduce the bug?** (as minimally and precisely as possible)
On a Windows machine, you should have WSL2 with Ubuntu. I have a droplet running on DigitalOcean where I reverse tunneled to port 5000 and should be able to authenticate with the registry there.

Note: My registry address resolves to 127.0.1.1 instead of 127.0.0.1

My devspace.yaml (trimmed some of it for privacy reasons):

```
version: v2beta1
name: localenv

vars:
  IMAGE: ${REGISTRY}/objectstorage

images:
  objectstorage:
    image: "${IMAGE}"
    dockerfile: Dockerfile
    docker:
      args:
        - "--platform=linux/amd64"

dev:
  objectstorage:
    labelSelector:
      app.kubernetes.io/component: objectstorage
    ports:
      - port: "4000:4000"

pipelines:
  dev:
    run: |
      create_deployments objectstorage
      echo "objectstorage deployed"
  connect:
    run: |
      start_dev objectstorage

  build:
    run: |
      make build
      build_images objectstorage
      echo "objectstorage built"
```

**Local Environment:**

* DevSpace Version:  6.2.1
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: digitalocean
* Kubernetes Version:
  Client Version: v1.25.4
  Kustomize Version: v4.5.7
  Server Version: v1.23.8+k3s1

**Anything else we need to know?**

I set REGISTRY in my env vars to be my `hostname`:5000
