### ISSUE TITLE
devspace dev command terminated with exit code 139

### ISSUE THREAD

**Issue by GDXbsv** [devspace-sh/devspace#2448]
**What happened?**
Devspace can not sync with error `start_dev: initial sync: Sync - connection lost: command terminated with exit code 139` with amd64 container in arm64 cluster.
In directory i see:

```
ls -la
total 468444
drwxr-xr-x 2 root root      4096 Dec  1 08:51 .
drwxr-xr-x 1 root root      4096 Nov  2 09:05 ..
-rw------- 1 root root 164651008 Dec  1 08:51 core
-rw-r--r-- 1 root root  28102656 Dec  1 08:44 qemu_devspacehelper_20221201-084439_162.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:44 qemu_devspacehelper_20221201-084439_182.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:44 qemu_devspacehelper_20221201-084439_189.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:45 qemu_devspacehelper_20221201-084504_207.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:45 qemu_devspacehelper_20221201-084504_227.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:45 qemu_devspacehelper_20221201-084504_234.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084616_248.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084617_267.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084617_274.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084625_288.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084626_308.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:46 qemu_devspacehelper_20221201-084626_315.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:48 qemu_devspacehelper_20221201-084811_328.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:48 qemu_devspacehelper_20221201-084816_331.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:51 qemu_devspacehelper_20221201-085145_344.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:51 qemu_devspacehelper_20221201-085146_364.core
-rw-r--r-- 1 root root  28102656 Dec  1 08:51 qemu_devspacehelper_20221201-085146_371.core
```

Where qemu_devspacehelper is what appear after each attempt.

**What did you expect to happen instead?**
Success sync

**How can we reproduce the bug?** (as minimally and precisely as possible)
Mac ARM (m1/m2)

```
brew install colima docker k3d devspace 
colima start --cpu 7 --memory 7 --disk 100 --runtime docker
k3d cluster create
Then try to sync with amd64 image
```

My devspace.yaml:

```
version: v2beta1
name: devspace-all
vars:
  DEVSPACE_ENV_FILE: ".env"
  DEVSPACE_FLAGS: '-n all'
  GITLAB_CONTAINER_REGISTRY_USER:
    question: gitlab container registry username?
  GITLAB_CONTAINER_REGISTRY_PASS:
    question: gitlab container registry password?
    password: true
  QUAY_CONTAINER_REGISTRY_USER:
    question: quay container registry username?
  QUAY_CONTAINER_REGISTRY_PASS:
    question: quay container registry password?
    password: true
  COMPOSER_GITHUB_TOKEN:
    question: composer github token?
    password: true
  XDEBUG_HOST:
    question: xdebug host? [host.docker.internal -- WIN] [172.17.0.1 - LIN] [MAC - see in ifconfig or in your network connection]
    default: "172.17.0.1"
  CORE_PATH:
    question: path to core? [./core] | [../core] | [/global/path/core]

deployments:
  docker-core:
    helm:
      chart:
        name: ./cluster/chart
      values:
       credentials:
         - registry: quay.io
           username: "${QUAY_CONTAINER_REGISTRY_USER}"
           password: "${QUAY_CONTAINER_REGISTRY_PASS}"
         - registry: registry.gitlab.com
           username: "${GITLAB_CONTAINER_REGISTRY_USER}"
           password: "${GITLAB_CONTAINER_REGISTRY_PASS}"
         - registry: gitlab.com
           username: "${GITLAB_CONTAINER_REGISTRY_USER}"
           password: "${GITLAB_CONTAINER_REGISTRY_PASS}"


dev: {}

commands:
  database-refresh:
    command: |-
      ./bin/setupDatabaseKube.sh
    description: Refresh slim damp and migration on DB.

profiles:
  - name: core
    merge:
      deployments:
        docker-core:
          helm:
            values:
              develop:
                core: 1
      dev:
        core:
          labelSelector:
            io.kompose.service: core
          ssh:
            enabled: true
          devImage: registry.gitlab.com/gotphoto/platform/core/app:develop-latest
          patches: &core-patches
            - op: remove
              path: spec.containers.lifecycle
          env: &core-envs
            - name: XDEBUG_CONFIG
              value: "client_host=${XDEBUG_HOST}"
          sync:
            - path: ${CORE_PATH}:/srv/www
              printLogs: true
#              excludeFile: .gitignore
              excludePaths:
                - .cache_composer/
                - /app/tmp/
                - ${CORE_PATH}/app/tmp/
                - .git
              uploadExcludePaths:
                - ${CORE_PATH}/vendor/
                - /vendor/
                - ${CORE_PATH}/Plugin/
                - /Plugin/
                - ${CORE_PATH}/app/tmp/
                - /app/tmp/
              downloadExcludePaths:
                - /.cache_composer/
                - /app/tmp/
              onUpload:
                # These post-sync commands will be executed after DevSpace synced changes to the container in the given order
                exec:
                  - command: |-
                      composer config github-oauth.github.com ${COMPOSER_GITHUB_TOKEN}
                    onChange: ["composer.lock"]
                  - command: |-
                      composer install --no-interaction --prefer-dist
                    onChange: ["composer.lock"]
                  - command: "chmod -R 0777 ./"      # string   | Command that should be executed after DevSpace made changes
        core-commands:
          labelSelector:
            io.kompose.service: core-commands
          devImage: registry.gitlab.com/gotphoto/platform/core/app:develop-latest
          patches: *core-patches
          env: *core-envs
        core-order-events:
          labelSelector:
            io.kompose.service: core-order-events
          devImage: registry.gitlab.com/gotphoto/platform/core/app:develop-latest
          patches: *core-patches
          env: *core-envs
```

**Local Environment:**

* DevSpace Version: devspace version 6.2.1
* Operating System: mac
* ARCH of the OS:  ARM64
  **Kubernetes Cluster:**
* Local: k3d
* Kubernetes Version: Client Version: v1.25.4
  Kustomize Version: v4.5.7
  Server Version: v1.24.6+k3s1

**Anything else we need to know?**
