### ISSUE TITLE
get_flag prints double value if var is defined

### ISSUE THREAD

**Issue by pratikjagrut** [devspace-sh/devspace#2464]
**What happened?**
`get_flag` should print the value of the flag once.

**What did you expect to happen instead?**
`get_flag` prints the value of the flag twice.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: double-flag

profiles:
  - name: local
  - name: test

pipelines:
  deploy:
    run: |-
      echo $(get_flag "profile")
      echo $(get_flag "force-deploy")
vars:
  DEVSPACE_FLAGS: --namespace double-flag
```

```
$ devspace deploy --profile local --profile test
local test local test
false
```
