### ISSUE TITLE
"name" field is required for v1 schemas which breaks backward compatibility with v5 of devspace

### ISSUE THREAD

**Issue by white-hat** [devspace-sh/devspace#2493]
After upgrading to v6.2.4 from version v5.18.5 I can no longer import `v1beta11` version of `devspace.yaml` as a parent profile

For example, if my local `devspace.yaml` has the following lines

```
version: v1beta11
profiles:
  - name: my_local_profile
    parents:
      - profile: some_remote_profile
        source:
          path: ./parent
```

and `devspace.yaml` at `./parent` has the following structure

```
version: v1beta11
profiles:
  - name: some_remote_profile

...
```

I expect devspace v6.2.4 to successfully import this remote profile, instead I'm getting

```
fatal load parent profile some_remote_profile: you need to specify a name for your devspace.yaml
```

I could add `name: my_remote_devspace_config` to the remote profile, but that breaks it for users who still use v5.18.5
