### ISSUE TITLE
Never asking user for input for environment variables

### ISSUE THREAD

**Issue by vjanz** [devspace-sh/devspace#2497]
**What happened?**
I am trying to add environment variables that would require user inputs to fill. In this case I would like the DB_PASSWORD to be provided in a dynamic way rather than hard coding in the devspace.yaml.

**What did you expect to happen instead?**
I excepted that devspace would prompt for user input asking me for `DB_PASSWORD` environment variable as it's not provided in other ways, but it doesn't and it just continues the process. I was excepting that the tool first asks me for the input, then continues to build the images based on my input (or append to the container in k8s).

I tried

```
$ devspace reset vars
 
```

and

```
$ devspace dev -b

or 

$  devspace deploy
```

or completely deleting the .devspace folder, but it's the same, the process never asks for input

**How can we reproduce the bug?**

My devspace.yaml:

```
version: v2beta1
name: docker-compose

vars:
  name: DB_PASSWORD
  question: "Please enter DB PASSWORD:"
  source: input
  password: true


images:
  backend:
    image: my_service
    dockerfile: Dockerfile
    entrypoint:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000


deployments:
  backend:
    helm:
      values:
        containers:
          - env:
              - name: DB_PASSWORD
                value: ${DB_PASSWORD}
            image: my_service
            name: my_service_test
            volumeMounts:
              - containerPath: /usr/src/app
                volume:
                  name: volume-1
                  readOnly: false
        service:
          ports:
            - containerPort: 8000
              port: 8000
              protocol: TCP
        volumes:
          - emptyDir: { }
            name: volume-1

dev:
  backend:
    labelSelector:
      app.kubernetes.io/component: backend
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    sync:
      - path: ./:/usr/src/app
        startContainer: true
    ports:
      - port: "8000"
```

**Local Environment:**

* DevSpace Version: 6.2.4
* Operating System: Linux
* ARCH of the OS: AMD64 | ARM64 | i386
  **Kubernetes Cluster:**
* Cloud Provider: AWS
* Kubernetes Version: 1.21.5

Is there something I'm missing as I am quite new to this tool. Thank you everyone in advance.

**Comment by 89luca89** [comment]
Hi @vjanz 

I think the problem here is how you declared the variable:

```yaml

vars:
  name: DB_PASSWORD
  question: "Please enter DB PASSWORD:"
  source: input
  password: true
  ```
  
  This won't work, you need to have DB_PASSWORD as the key:
  
  ```yaml
  
vars:
  DB_PASSWORD:
    question: "Please enter DB PASSWORD:"
    source: input
    password: true
  ```
  
  This version works from my testing, can you confirm it works for you too?
  Thanks!
