### ISSUE TITLE
Enable int values on maxSurge and maxUnavailable, as well as percent values.

### ISSUE THREAD

**Issue by pablorsk** [devspace-sh/devspace#2517]
**Is your feature request related to a problem?**

Let's assume this deployment:

```
my_deployment:
    helm:
        values:
            containers:
                  image: my_app:1.0.0
                  name: cool
            rollingUpdate:
                enabled: true
                maxSurge: 1%
                maxUnavailable: 0%
            replicas: 1
            autoScaling:
                horizontal:
                    averageCPU: 200m
                    maxReplicas: 10
```

Suppose we have autoscaled to 10 replicas. When I deploy, all 10 replicas are recreaded simultaneously. I think is because `maxSurge:1%` of `replicas:1` is 1; and 1 is the 100% of pods (based on K8S documentation).

I think, if I put `maxSurge:1` the problem will be solved. Now, if I put `maxSurge:1` I receive:

```
Error: UPGRADE FAILED: cannot patch "my_deployment" with kind Deployment: Deployment.apps "my_deployment" is invalid: spec.strategy.rollingUpdate.maxSurge: Invalid value: intstr.IntOrString{Type:1, IntVal:0, StrVal:"1"}: a valid percent string must be a numeric string followed by an ending '%!'(MISSING) (e.g. '1%!'(MISSING),  or '93%!'(MISSING), regex used for validation is '[0-9]+%!'(MISSING))
```

**Which solution do you suggest?**

Enable int values on `maxUnavailable` and `maxSurge`, like [K8S documentation](https://kubernetes.io/es/docs/concepts/workloads/controllers/deployment/#escalado-proporcional).

**Which alternative solutions exist?**

Maybe my problem is with the cluster; but if integer values ​​are enabled devspace could accept values ​​allowed by K8s.

**Additional context**

```
$ devspace -v
devspace version 6.2.2
```
