### ISSUE TITLE
issue where imageSelector and containerName can't be used together

### ISSUE THREAD

**Issue by georgemilojevic** [devspace-sh/devspace#2519]
**What happened?**
On new version 6.25 the issue which was resolved on release v5.18.4 is now present again.
From the release 5.18.4: Fixed an issue where imageSelector and containerName couldn't be used together

**What did you expect to happen instead?**
When running devspace dev or devspace dev --namespace=<namespace-name> I would expect a successful build

**How can we reproduce the bug?** (as minimally and precisely as possible)
run: `devspace dev` with devspace.yaml file containing both image and label selector
My devspace.yaml:

```
sync:
  - imageName: app
    containerName: appName
    labelSelector:
      app.kubernetes.io/instance: instance
      app.kubernetes.io/name: name
version: v1beta9
...
```

**Local Environment:**

* DevSpace Version: 6.25
* Operating System: mac
* ARCH of the OS: ARM64 (M1 apple silicon)
  **Kubernetes Cluster:**
* Cloud Provider: google
* Kubernetes Version: \[use `kubectl version`\]

**Anything else we need to know?**
Using version 5.18.4 now and the build has worked as expected
