### ISSUE TITLE
Past errors are displayed

### ISSUE THREAD

**Issue by a-candiotti-pvotal** [devspace-sh/devspace#2524]
**What happened?**

When I get errors after "Waiting for pod to become ready..."
I get errors from previous runs.
I noticed that because the number of errors displayed is accumulating.

Example :

I get a lot of

`Pod {podname}: Readiness probe failed: HTTP probe failed with statuscode: 503 (Unhealthy)`

For some reason, and they accumulate.

**What did you expect to happen instead?**

Errors regarding the current run being displayed.

**How can we reproduce the bug?** (as minimally and precisely as possible)

In my ase I deploy with argocd in the cluster and then try to connect to an existing container.

My devspace.yaml:

```
version: v2beta1
name: myappname

pipelines:
  dev:
    run: |-
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      start_dev myappname # 4. Start dev mode "app" (see "dev" section)

dev:
  myappname:
    namespace: myappname
    # Needed to avoid replacing migrate container
    labelSelector:
      app: myappname
    devImage: ghcr.io/loft-sh/devspace-containers/go:1.18-alpine
    sync:
      - path: ./
    command: ["ping", "127.0.0.1"]
    logs: {}
    ssh:
      enabled: true
    resources:
      requests:
        cpu: 1
        memory: 1Gi

hooks:
  - events: ["before:deploy"]
    command: if [ -d '.devspace/chart-repo/.git' ]; then cd ".devspace/chart-repo" && git pull origin develop; else mkdir -p .devspace/chart-repo; git clone --single-branch --branch develop git@github.com:pvotal-tech/pvotal-common-helm_chart-svc.git .devspace/chart-repo; fi
  - events: ["after:deploy"]
```

**Local Environment:**

* DevSpace Version:  6.2.5
* Operating System: mac
* ARCH of the OS: ARM64
  **Kubernetes Cluster:**
* Cloud Provider: k3d
* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T17:00:51Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/arm64"}
```

**Anything else we need to know?**
