### ISSUE TITLE
inlineManifest: cannot unmarshal an object into string

### ISSUE THREAD

**Issue by Orgil** [devspace-sh/devspace#2544]
**What happened?**

```
deployments:
  test:
    inlineManifest:
        apiVersion: v1
        kind: Secret
        metadata:
          name: test
        type: Opaque
        data:
          SECRET: $(echo '${SECRET}' | base64)
```

`cannot unmarshal an object into string` error given. if i add `|-` at the end of `inlineManifest` i can not use expression in the value.

**Local Environment:**

* DevSpace Version: 6.2.5
* Operating System: mac 11.6.1
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: docker-desktop
* Kubernetes Version: 1.24

**Comment by 89luca89** [comment]
Hi @Orgil I'll take a look at this :+1:

**Comment by 89luca89** [comment]
so @Orgil 

using `|-` is mandatory, `inlineManifest` is meant to be a `block` of text, containing the manifests so:

```
deployments:
  test:
    inlineManifest: |-
        apiVersion: v1
        kind: Secret
        metadata:
          name: test
        type: Opaque
        data:
          SECRET: $(echo '${SECRET}' | base64)
```

this is the correct way to use it, I'll need to investigate why the inline shell is not working
