### ISSUE TITLE
tail --pid unkown argument

### ISSUE THREAD

**Issue by Timoses** [devspace-sh/devspace#2571]
**What happened?**
The app-devspave dev container logs:

```
############### Restart container ###############

No screen session found.
tail: unrecognized option: pid=2041
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.

Usage: tail [OPTIONS] [FILE]...

Print last 10 lines of FILEs (or stdin) to.
With more than one FILE, precede each with a filename header.

        -c [+]N[bkm]    Print last N bytes
        -n N[bkm]       Print last N lines
        -n +N[bkm]      Start on Nth line and print the rest
                        (b:*512 k:*1024 m:*1024^2)
        -q              Never print headers
        -v              Always print headers
        -f              Print data as file grows
        -F              Same as -f, but keep retrying
        -s SECONDS      Wait SECONDS between reads with -f

Container exited. Will restart in 7 seconds...
```

**What did you expect to happen instead?**
Nothing special, I am still working to understand devspace.
Just wondering whether this error has something to do that the container/pod does not restart when I change a file under `./app/` path.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
  version: v2beta1
  name: pipes

  # This is a list of `pipelines` that DevSpace can execute (you can define your own)
  pipelines:
    # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
    deploy:
      run: |-
        run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
        ensure_pull_secrets --all                         # 2. Ensure pull secrets
        build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
        create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"
    # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
    dev:
      run: |-
        run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
        ensure_pull_secrets --all    # 2. Ensure pull secrets
        create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
        start_dev app                # 4. Start dev mode "app" (see "dev" section)

  # This is a list of `deployments` that DevSpace can create for this project
  deployments:
    app:
      kubectl:
        inlineManifest: |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: pipes
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: pipes
            template:
              metadata:
                labels:
                  app: pipes
              spec:
                containers:
                - args:
                  - sleep
                  - "999999"
                  image: docker.io/timoses/pipes
                  name: pipes


  images:
    app:
      image: docker.io/timoses/pipes
      dockerfile: Containerfile

  # This is a list of `dev` containers that are based on the containers created by your deployments
  dev:
    app:
      imageSelector: docker.io/timoses/pipes
      command: ["/pipes"]
      restartHelper:
        inject: true
      # Replace the container image with this dev-optimized image (allows to skip image building during development)
~     devImage: ghcr.io/loft-sh/devspace-containers/go:1.20-alpine
      # Sync files between the local filesystem and the development container
      sync:
~       - path: ./app/
          onUpload:
            restartContainer: true
          disableDownload: true
      # Open a terminal and use the following command to start it
      terminal:
        command: ./devspace_start.sh
      # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
      ssh:
        enabled: true
      # Make the following commands from my local machine available inside the dev container
      proxyCommands:
        - command: devspace
        - command: kubectl
        - command: helm
        - gitCredentials: true
      # Forward the following ports to be able access your application via localhost
      ports:
        - port: "2345"

  # Use the `commands` section to define repeatable dev workflows for this project
  commands:
    migrate-db:
      command: |-
        echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
        echo 'Anyone using this project can invoke it via "devspace run migrate-db"'

  # Define dependencies to other projects with a devspace.yaml
  # dependencies:
  #   api:
  #     git: https://...  # Git-based dependencies
  #     tag: v1.0.0
  #   ui:
  #     path: ./ui        # Path-based dependencies (for monorepos)
```

**Local Environment:**

* DevSpace Version: \[use `devspace --version`\] devspace version 6.3.0
* Operating System: windows | linux | mac   linux!
* ARCH of the OS: AMD64 | ARM64 | i386   AMD64
  **Kubernetes Cluster:**
* Cloud Provider: local k3s cluster
* Kubernetes Version: \[use `kubectl version`\]
* Client Version: [version.Info](http://version.Info){Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
  Kustomize Version: v4.5.4
  Server Version: [version.Info](http://version.Info){Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

**Anything else we need to know?**
Currently trying out devspace. Want to hot reload golang app in container when changing app code on host.
