### ISSUE TITLE
multiple pod sync issue

### ISSUE THREAD

**Issue by Orgil** [devspace-sh/devspace#2573]
**What happened?**  
In order to work on multiple pod simultaneously, i do `devspace sync --config=devspace.yaml` on every pod. It used to work on 6.1 series releases but starting from 6.2 every new sync stops other pod sync with below error.

```
Restarting because: Sync - connection lost to pod <pod> - command terminated with exit code 137
```
So the pod restarted but stuck in `still waiting mode` waiting for initial sync complete.

**What did you expect to happen instead?**  
`devspace sync` doesn't affect other sync.

**Local Environment:**  
- DevSpace Version: 6.3
- Operating System: mac
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: local k3s
- Kubernetes Version: 1.25

**Anything else we need to know?**

**Comment by FabianKramm** [comment]
Hey @Orgil ! Thanks for reporting this issue, mhh that is strange, is there any other information why this could happen besides the command terminated message?

**Comment by Orgil** [comment]
I do have fairly complex setup working on multi microservice environment crossing different namespaces. Using many different areas of devspace, i believe resolving this case could solve many different individual cases related to sync and initial sync. Pods are private but i'll try to illustrate my flow.

Lets say we have 3 different pods.
1. main <- handling all public request, only gateway to public
2. service-a <- written in nodejs, using nodemon, no need restart helper in development
3. service-b <- written in go, need restart helper while in development

Here are the basic configs for each pods dev section.

main - dev section
```
main-service:
  imageSelector: main-service
  devImage: node
  command: ["npm", "dev"]
  logs: {}
    sync:
      - path: ./
        initialSync: preferLocal
        disableDownload: true
        startContainer: true
        printLogs: true
        onUpload:
          exec:
            - command: "npm install"
              onChange: ["./package.json"]
  service-a:
    labelSelector:
      service: service-a
    logs: {}
  service-b:
    labelSelector:
      service: service-b
    logs: {}
```

service-a
```
service-a:
  imageSelector: service-a
  devImage: node
  command: ["npm", "dev"]
  logs: {}
    sync:
      - path: ./
        initialSync: preferLocal
        disableDownload: true
        startContainer: true
        printLogs: true
        onUpload:
          exec:
            - command: "npm install"
              onChange: ["./package.json"]
```

service-b
```
  service-b:
    imageSelector: service-b
    devImage: golang:1.19
    command: ["go", "run", "cmd/main.go"]
    logs: {}
    env:
      - name: DB_NAME
        value: ${DB_NAME} <-------- if i use 'service-b'  here, it will replaced with 'service-b:<TAG>'
    restartHelper:
      inject: true
    sync:
      - path: ./
        disableDownload: true
        startContainer: true
        printLogs: true
        onUpload:
          restartContainer: true
          exec:
            - command: "go mod download"
              onChange: ["./go.mod", "./go.sum"]
```

Here is couple issues that i have currently.
1. using variable same as image name, it replaced with tagged image name. Currently using different words for name and variables. no big issue.
2. Instead of `devspace dev` on each of them, i do `devspace sync --config=devspace.yaml` on `service-a` and `service-b`.  Then `devspace dev` on main. It was streaming all service logs, but starting from `6.2` starting main service break others sync as described before. Once it is break, pods are restarted and waiting for sync, so stuck in `(still waiting)` mode. If i start sync again on one of the service it will break main's sync etc.
3. If kubernetes restarts in somehow, pods are initialized with modified container but stuck in still waiting mode, if i don't resync them. I think it is because of `startContainer: true` config, however without it dev images are not work also. there is also `waitInitialSync` config, confused between `waitInitialSync` and `startContainer`.

Tried my best to explain, hope you get some idea.

**Comment by FabianKramm** [comment]
@Orgil thanks a lot for the throughout explanation, I'm not sure what change has caused this to break, but seems like we need to investigate this.

**Comment by lizardruss** [comment]
@Orgil Could you try this again with the `--debug` flag on both `devspace dev` and `devspace sync` commands and share the logs?

FWIW, as I tried reproducing this, I needed to change the sync paths to `./:/app` to avoid syncing to the root of the containers.

Are the `dev` configs shared above in separate `devspace.yaml` files, or all together?

**Comment by Orgil** [comment]
@lizardruss @FabianKramm i've tried to investigate it little deeper with much config combination possible. I think i found the problem.
```        
startContainer: false
waitInitialSync: true <---------- setting it true or false only affect streaming log.
```
I'm using official nodejs image to replace pod for dev environment.

```
dev:
  api-service:
    imageSelector: api-service
    devImage: node:18.8
    workingDir: /usr/app
    command: ["npm", "dev"]
    logs: {}
    persistPaths:
      - path: /usr/app
        volumePath: api-service
    persistenceOptions:
      size: 5Gi
      storageClassName: local-storage
      accessModes:
        - ReadWriteMany
      name: pnpm-pvc
    sync:
      - path: ./ <------- set ./:./ because workingDir: /usr/app
        initialSync: preferLocal
        startContainer: false
        # waitInitialSync: true
        printLogs: true
        disableDownload: true
        onUpload:
          exec:
            - command: "npm install"
              onChange: ["./package-lock.json"]
  front-service:
    labelSelector:
      service: front-service
    logs: {}
  back-service:
    labelSelector:
      service: back-service
    logs: {}

```

Following happened:

As of fresh start, sync path is empty. 
`startContainer: false`
`devspace dev` - didn't work. sync not started and not waiting it, just start `npm dev` command ends up in CrashLoopBack state.

`startContainer: true`
`devspace dev` - works as expected. Wait for sync and filled up sync path then starts.

`kubectl rollout deployment api-service-devspace` restarting pod will stuck `(Still waiting...)` mode because of `startContainer: true`. So i need to run 'devspace dev` or 'devspace sync' to make it work. Think about that i need to run sync on every replaced pod in order to start them.

Once sync path is filled up, i need to set it back to `startContainer: false` and re-run 'devspace dev' to take effect. Then everything works fine. The replaced pod starts with or without sync.

I'm having multiple services each one having similar `devspace.yaml`.

**Comment by lizardruss** [comment]
@Orgil

The first scenario with `startContainer: false` I would expect it to fail because the `node:18.8` image will not contain your `package.json` and thus running `npm run dev` would fail, thus the `CrashLoopBackoff` state.

The second scenario with `startContainer: true` will instruct DevSpace to sync files before starting the container. Therefore your `package.json` is present and things work when the container starts with `npm run dev`

In the third scenario, you're scaling up the "dev image" deployment manually with `kubectl rollout`, which will scale up the deployment without syncing the required `package.json` and crash until these files are synced with `devspace dev` or `devspace sync`, as you observed.

A workflow that might work better if you only want to develop a subset of your services:
1. For each service you want to actively develop run `devspace dev`
2. For each service you'd like to deploy without developing, run `devspace deploy`.
3. If you've previously run `devspace dev` on a service that you're no longer developing, run `devspace reset pods` to return it to how it would be deployed using `devspace deploy`.

With the above workflow you can leave `startContainer: true` and avoid modifying the `devspace.yaml`.

I've put together an [example repo](https://github.com/lizardruss/devspace-debug/tree/multi-sync) that reflects my current understanding of this issue. Please review and let me know if I'm still missing something.

**Comment by Orgil** [comment]
@lizardruss i created [pull request](https://github.com/lizardruss/devspace-debug/pull/1) on your example repo to simulate real project.
To make it clear here I have 2 problems. 
1. Simultaneous sync problem. As i reported [previously](https://github.com/devspace-sh/devspace/issues/2573#issue-1600503148), it works fine with `devspace 6.1.1`, breaks after that. When sync breaks it restarts all other replaced pods.  Try to run `devspace dev` simultaneously.

Actual error
```
error Sync Error on /Volumes/SSD/Projects/devspace-debug/front-service: Sync - connection lost to pod development/front-service-devspace-875b76b5c-ktl8r:  command terminated with exit code 137
error Restarting because: Sync - connection lost to pod development/front-service-devspace-875b76b5c-ktl8r:  command terminated with exit code 137
```

2. Pod starts with `startContainer:false` doesn't start sync initially.
Let's say I actively working on those 3 projects. All 3 services talk to each other so all must have working condition. Here is what i do daily.

- since i'm using local k8s, my local k8s starts when i my pc start.
- all 3 projects stuck in `(Still waiting...)`, because `startContainer: true`
-- i can `devspace sync` or `devspace dev` on each service just to start it even i need to develop on one.
-- i can `devspace reset pods` after development but it tears down pvc, so need to install all dependencies again.
-- i can change `startContainer: false`. It works if mounted pvc filled up before, doesn't work if pvc not filled up.

Try to run example repo with fresh start, when no pvc created yet. it gives me following:
```
deploy:front-service Deploying chart component-chart (front-service) with helm...
deploy:front-service Deployed helm chart (Release revision: 6)
deploy:front-service Successfully deployed front-service with helm
dev:front-service Waiting for pod to become ready...
dev:front-service Pod front-service-devspace-6d8fc48fd4-8q7jg: Back-off restarting failed container (BackOff)
dev:front-service DevSpace is waiting, because Pod front-service-devspace-6d8fc48fd4-8q7jg has status: Init:0/2
dev:front-service Pod front-service-devspace-6d8fc48fd4-8q7jg has critical status: Error. DevSpace will continue waiting, but this operation might timeout
dev:front-service Pod front-service-devspace-6d8fc48fd4-8q7jg has critical status: Error. DevSpace will continue waiting, but this operation might timeout
dev:front-service Pod front-service-devspace-6d8fc48fd4-8q7jg has critical status: CrashLoopBackOff. DevSpace will continue waiting, but this operation might timeout
dev:front-service Selected pod front-service-devspace-6d8fc48fd4-8q7jg
dev:front-service sync  Inject devspacehelper...
start_dev: start sync: inject devspace helper: exec: unable to upgrade connection: container not found ("container-0")
fatal exit status 1
```
i believe there is race condition happened when pvc empty, `startContainer: false`.

Hope it clear things up.

**Comment by lizardruss** [comment]
> Pod starts with startContainer:false doesn't start sync initially.

This part is considered working properly, since it's telling DevSpace not to start the container.

What you can do instead is to use `onUpload.restartContainer: true`, for example:
```yaml
onUpload:
  restartContainer: true
  exec:
    - command: "npm install"
      onChange: ["./package-lock.json"]
```

The other issue is that (at least in the example repo) all three are syncing their files to the same directory on the same PVC, so they're potentially overwriting each other's files. To fix that, I've changed the `workingDir` for each to a subdirectory of `/usr/app`. They'll still use the same PVC, but will have different `node_modules` etc. I think `pnpm` has some magic to prevent duplication, or may need additional configuration to optimize it.

Finally, the last thing to look out for is pods restarting after running `devspace dev`. Since all deployments are sharing a PVC, the replica sets are scaled down to release the PVC. This was a fix to a different issue, and we may be able to improve the handling of `ReadWriteMany` PVCs, but we would need to do extensive testing. For the time being the pods will restart after each `devspace dev`, but should automatically re-connect to the original PVC and restart.

I've pushed those changes to the example repository, please give it a try and see if it's acceptable.
