### ISSUE TITLE
disableDependencyUpdate should be optional in devspace-schema.json

### ISSUE THREAD

**Issue by meyfa** [devspace-sh/devspace#2588]
**What happened?**

My IDE complains that the Helm deployment config should have a `disableDependencyUpdate` key, since it's marked as required in the schema. See:

[https://github.com/devspace-sh/devspace/blob/3dc4ad3396205d7ad11c2508c756e81129e29081/devspace-schema.json#L754-L756](https://github.com/devspace-sh/devspace/blob/3dc4ad3396205d7ad11c2508c756e81129e29081/devspace-schema.json#L754-L756)

This is not actually correct - `disableDependencyUpdate` defaults to false, and can safely be omitted. See:

[https://github.com/devspace-sh/devspace/blob/3dc4ad3396205d7ad11c2508c756e81129e29081/devspace-schema.json#L748-L751](https://github.com/devspace-sh/devspace/blob/3dc4ad3396205d7ad11c2508c756e81129e29081/devspace-schema.json#L748-L751)

**What did you expect to happen instead?**

The schema shouldn't contain `disableDependencyUpdate` as a required property.

**How can we reproduce the bug?** (as minimally and precisely as possible)

Use a devspace.yaml including a section like the one below, and let your IDE / some other tool verify it against the schema:

My devspace.yaml:

```
version: v2beta1
name: my-app

deployments:
  my-app:
    namespace: ${DEVSPACE_NAMESPACE}
    helm:
      chart:
        name: ${DEVSPACE_NAME}
        repo: https://gitlab.example.com/api/v4/projects/22/packages/helm/charts
        username: ${GITLAB_USERNAME}
        password: ${GITLAB_ACCESS_TOKEN}
      valuesFiles: ["dev/values.yaml"]
```

**Local Environment:**

* DevSpace Version: 6.3.0
* Operating System: windows
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: local
* Kubernetes Version: 1.25.4

**Anything else we need to know?**
