### ISSUE TITLE
Allow require to not check version but just that the command is installed and can be executed

### ISSUE THREAD

**Issue by jordiclariana** [devspace-sh/devspace#2595]
**Is your feature request related to a problem?**
No, it is somehow an enhancement on top of an existing feature (require.command)

**Which solution do you suggest?**
Right now the `require.commands[].version` is a required field to be configured when setting up a new required command. My proposal would be to add another field that if existing, bypasses `version` field verification and just executed the command (with the given `versionArgs`) and assess that its execution didn't throw any error. On top of it, `versionRegEx` can also assess that it matches the output of the command.

Obviously, using `versionArgs` and `versionRegEx` to not assess the version but to assess that the command exists and is executed properly, is confusing, so maybe the alternative can be add new fields that can be complementary to the version check (they can work together, doing different checks on top of the same required command). Example:

```
require:
  commands:
  - name: git
    version: '>=2.25'
    versionRegEx: 'version (v?\\d+\\.\\d+\\.\\d+)'
    executeArgs: ['git', '--help']
    executeRegEx: '^usage: git'
```

Either version, executeRegEx or both must be declared. `executeRegEx` must match the output of the execution of the command (`name`) with `executeArgs` as arguments of the command itself.

**Which alternative solutions exist?**
Just stay like it is right now

**Additional context**
In my, opinion this makes the `require` to have more sense, since you don't always need to check the version, but some times just that the command is installed and available. This cannot be done using `version` since its syntax is strict.
