### ISSUE TITLE
For dev container pod replacement, support scaleDownTarget() of custom resources, beyond ReplicaSet, Deployment, and StatefulSet

### ISSUE THREAD

**Issue by elliottsj** [devspace-sh/devspace#2618]
**Is your feature request related to a problem?**

Yes. My application uses a custom Kubernetes controller combined with custom resources to create deployments.

e.g.

```
apiVersion: vx.cohere.ai/v1alpha1
kind: Service
metadata:
  name: myapp
  namespace: mynamespace
  labels:
    app.kubernetes.io/name: myapp
spec:
  replicas: 1
  podSpec:
    containers: # ...
```

This "VX Service" is watched by VX Controller, which updates a corresponding Deployment for myapp:

```
(VX Service CRDs) <--watches-- (VX Controller) --updates--> (Kubernetes Deployments)
```

The problem is that DevSpace is not aware of this mechanism, so when DevSpace tries to scale down the Deployment with

```
kubectl scale deployment/myapp --replicas=0
```

, VX Controller will immediately scale it back up to `replicas: 1`, and the Deployment will fail to be replaced by the desired `[old-object-name]-devspace` Deployment.

**Which solution do you suggest?**

VX Controller supports the `scale` command when the correct custom resource is specified, e.g. this command:

```
kubectl scale vxsvc/myapp --replicas=0
```

DevSpace should support a configuration option or custom command to scale custom resources. For example, something like:

```
dev:
  myapp:
    imageSelector: # ...
    devImage: # ...
    customResourceName: vxsvc/myapp
```

**Which alternative solutions exist?**

An option I am investigating is to modify VX Controller to watch for `kubectl scale deployment/*` events and update the corresponding VX Service appropriately. I am unsure at this moment whether it's possible and whether it would be a sound design decision, since introducing two-way synchronization of VX Services and Deployments could cause further problems.

**Additional context**

This function seems relevant: [https://github.com/devspace-sh/devspace/blob/294a386008d52a6ed58448f3c73e5f3ef3caeb00/pkg/devspace/services/podreplace/replace.go#L360](https://github.com/devspace-sh/devspace/blob/294a386008d52a6ed58448f3c73e5f3ef3caeb00/pkg/devspace/services/podreplace/replace.go#L360)

It appears to only support ReplicaSet, Deployment, and StatefulSet, but not custom resources.
