### ISSUE TITLE
Listing deployments does not consider releaseName

### ISSUE THREAD

**Issue by mschoenlaub** [devspace-sh/devspace#2626]
**What happened?**  
When setting a releaseName for a deployment based on helm charts, as here

```
deployments:
  kafka:
    helm:
      releaseName: ${DEVSPACE_NAME}-kafka
```

and then deploying it via `devspace deploy`, `devspace list deployments` cannot detect the correct status of the deployment.

The reason seems to be that it only uses the deployment name itself to compare against the deployed helm releases.

**What did you expect to happen instead?**  
I'd expect that `devspace list deployments` correctly matches helm releases with deployment configs, e.g. if `devspace deploy` succeeded, `devspace list deplyments` should list all deployments with a `DEPLOYED` status.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

```
version: v2beta1
name: quickstart

deployments:
  quickstart:
    helm:
      releaseName: "gotcha"
      values:
        containers:
        - image: loftsh/javascript:latest
```

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System: mac, linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: eks
- Kubernetes Version: Client Version: v1.24.2, Kustomize Version: v4.5.4, Server Version: v1.22.17-eks-48e63af

**Anything else we need to know?**  
We use the `releaseName` to inject some environment variable. With `devspace v5` this seemed to have worked fine, because the  deployment config was actually a list where we could set the name. Now it is an object and the keys are only allowed to contain alphanumeric characters, it seems.
