### ISSUE TITLE
Opening a project with PyCharm

### ISSUE THREAD

**Issue by plopezamaya** [devspace-sh/devspace#2628]
**What happened?**  
While using Pycharm 2022.1.4 on MacOs 13.1 (22C65) M1 I can open an SSH terminal but when I try to open a project inside  a kubernetes container I have the following error:
```
Command: "remote-dev-server.sh run "/app""
exitCode: "0"
stderr: 
---
stdout:
---
```

**What did you expect to happen instead?**  
IDE is opened with project on remote container

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Open PyCharm 2022.1.4 -> Remote Development -> SSH. Add a new connexion (ssh private key location is not shown but connexion was tested successfully) -> select IDE to use (PyCharm 2022.1.4) -> Select Project (depending on your WorkingDir and you sync in here it's /app) -> Download and start IDE
![Screenshot 2023-04-19 at 10 29 24](https://user-images.githubusercontent.com/131244390/233017510-2cbb8923-8a39-4aff-a2dc-09620ebc780e.png)

My devspace.yaml:
```
version: v2beta1
name: devspace-quickstart-python

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev pedro-dev                # 4. Start dev mode "pedro-dev" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"


# This is a list of `deployments` that DevSpace can create for this project
deployments:
  pedro-dev:
    # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
    helm:
      # We are deploying this project with the Helm chart you provided
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
      # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
      values:
        containers:
          - image: python:3.10
            name: dev
            tty: true
            resources:
              limits:
                memory: 2Gi
                cpu: 1
              requests:
                cpu: 0.5
                memory: 1Gi
        labels:
          developer: pedro
        tolerations:
          - key: "node.kubernetes.io/role"
            operator: "Equal"
            effect: "NoSchedule"
            value: "datascience"

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  pedro-dev:
    # Search for the container that runs this image
    labelSelector:
      developer: pedro
    namespace: data-science
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 1Gi
    # Sync files between the local filesystem and the development container
    sync:
      - path: ./:/app
        excludePaths:
          - env/
          - data/
        uploadExcludeFile: .dockerignore
    # Open a terminal and use the following command to start it
    workingDir: /app
    terminal:
      command: ./devspace_start.sh
    # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
    ssh:
      enabled: true
      localPort: 12345
    # Make the following commands from my local machine available inside the dev container
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true

# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'
```

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System:  MacOs 13.1 (22C65) M1
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: Client Version: v1.26.3 / Kustomize Version: v4.5.7 / Server Version: v1.24.10-eks-48e63af

**Anything else we need to know?**  
Here are the collected logs :
[gateway-logs-20230419-10312013168270559408050203.zip](https://github.com/devspace-sh/devspace/files/11270877/gateway-logs-20230419-10312013168270559408050203.zip)
