### ISSUE TITLE
localbuild says "Couldn't find a running docker daemon" in 6.3.2

### ISSUE THREAD

**Issue by igoooor** [devspace-sh/devspace#2635]
**What happened?**
`devspace build` fails with `localRegistry.localbuild = true` now that I am using 6.3.2.
I am using mac and before the updating introducing `localbuild` it was working fine.
Now I have that message:
`build_images: build images: error building image localhost:31457/proj-platform/nginx:latest: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
Obviously I have checked that docker is running

**What did you expect to happen instead?**
Docker image to be built locally as before

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
# All paths are relative to <project_root>/var/devspace
version: v2beta1

name: proj-platform

images:
  php:
    image: registry.local.gd:22345/proj-platform/php
    tags:
      - latest
    dockerfile: ../../.ops/env/base/php/docker/Dockerfile
    context: ../../.ops/env/base/php/docker/
    buildArgs:
      ...
  nginx:
    image: registry.local.gd:22345/proj-platform/nginx
    tags:
      - latest
    dockerfile: ../../.ops/env/base/nginx/docker/Dockerfile
    context: ../../.ops/env/base/nginx/docker/
  node:
    image: registry.local.gd:22345/proj-platform/node
    tags:
      - latest
    dockerfile: ../../.ops/env/global/node/docker/Dockerfile
    context: ../../app/metrics

deployments:
  proj-traefik-platform:
    helm:
      chart:
        name: ../../.ops/helm-traefik
      values:
        ...
  proj-platform:
    helm:
      chart:
        name: ../../.ops/helm
      values:
        ...

localRegistry:
  enabled: false
  localbuild: true

dev:
  publisher-php:
    labelSelector:
      app.kubernetes.io/component: php
      app.kubernetes.io/part-of: publisher
    reversePorts:
      - port: "9003:9003"
  redis:
    labelSelector:
      app: proj-platform-redis
      app.component-part: redis
    ports:
      - port: "30000:6379"
  elastic:
    labelSelector:
      app: proj-platform-elastic
      app.component-part: elastic
    ports:
      - port: "30001:9200"
  db:
    labelSelector:
      app: proj-platform-db
      app.component-part: mysql
    ports:
      - port: "30002:3306"
```

**Local Environment:**

* DevSpace Version: 6.3.2
* Operating System: mac
* ARCH of the OS: ARM64
  **Kubernetes Cluster:**
* Cloud Provider: kk3s
* Kubernetes Version: 1.24.10

**Anything else we need to know?**
