### ISSUE TITLE
Unable to deploy helm component chart - "invalid character <" error

### ISSUE THREAD

**Issue by hariprasadiit** [devspace-sh/devspace#2647]
**What happened?**
Unable to deploy component chart

```
error executing 'helm upgrade sendria --values /var/folders/yn/0q67fbxx21s0w9_v9tshx7hr0000gp/T/2010474375 --install --namespace vms-dev /Users/hari/.devspace/component-chart/component-chart-0.8.6.tgz --kube-context loft-vcluster_hari_hari_dev-cluster': Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: invalid character '<' looking for beginning of value
```

I'm using component chart to deploy simple docker container. there are no manifests to check if there are any invalid characters. If I deploy the same with helm cli it's working.

**What did you expect to happen instead?**
Successful deployment of component chart

**How can we reproduce the bug?** (as minimally and precisely as possible)
Simple deployment with Helm component chart

My devspace.yaml:

```
version: v2beta1
name: devops

vars:
  REGISTRY: registry.vizmo.dev
  ENV: dev

pullSecrets:
  pullsecret:
    registry: ${REGISTRY}

pipelines:
  build:
    run: |-
      run_dependency_pipelines --all --pipeline build
  deploy:
    run: |-
      ensure_pull_secrets pullsecret
      run_dependency_pipelines --all --pipeline deploy
  dev:
    run: |-
      ensure_pull_secrets pullsecret
      build_images --all
      create_deployments --all
      run_dependency_pipelines --all --pipeline dev --sequential

      start_dev --all
  purge:
    run: |-
      stop_dev --all
      run_dependency_pipelines --all --pipeline purge

dependencies:
  server: 
    path: ../vms-server
    pipeline: dev
    overwriteVars: true
  website: 
    path: ../vms-website
    pipeline: dev
    overwriteVars: true
  portal:
    path: ../vms-portal
    pipeline: dev
    overwriteVars: true
  touchless:
    path: ../vms-touchless
    pipeline: dev
    overwriteVars: true

deployments:
  sendria:
    helm:
      disableDependencyUpdate: false
      values:
        containers:
          - image: msztolcman/sendria:v2.2.2.0
        service:
          ports:
            - name: sendria-web
              port: 1080
            - name: sendria
              port: 1025

dev:
  parse-dashboard:
    labelSelector:
      app.kubernetes.io/component: parse-dashboard
    ports:
      - port: "4040"
        bindAddress: '0.0.0.0'
  sendria:
    labelSelector:
      app.kubernetes.io/component: sendria
    ports:
      - port: "1025"
      - port: "1080"
        bindAddress: "0.0.0.0"
  mongo:
    labelSelector:
      app.kubernetes.io/component: mongod
      app.kubernetes.io/instance: psmdb
      app.kubernetes.io/name: percona-server-mongodb
    ports:
      - port: "27017"
  shlink:
    labelSelector:
      app.kubernetes.io/component: shlink
    ports:
      - port: "1335"
        bindAddress: '0.0.0.0'
```

**Local Environment:**

* DevSpace Version: 6.3.2
* Operating System: mac
* ARCH of the OS: AMD64
  **Kubernetes Cluster:**
* Cloud Provider: other
* Kubernetes Version: 1.24.8
