### ISSUE TITLE
get k8s resource manifest from remote k8s cluster 

### ISSUE THREAD

**Issue by fengyeall111** [devspace-sh/devspace#2678]
**Is your feature request related to a problem?**  
# enviroment:
- remote k8s cluster  which has  deploy all microservices,include deployment,service, serviceaccount and so on。
-  code space for some microservice

I  scan devspace docs，but there is no way to do this thing:
using "devspace dev" without local k8s resouces or k8s resource generator. I'm curious about why the manifest is needed.
In our work,   a remote cluster can offer resource manifest, since it has deployed all microservices.So, why we must offer k8s resource 
manifest：all we need can offer by basic remote cluster. devspace can also get all resources from remote clusters.

For devoloper,  they don't need to know the details about ci/cd and k8s deploy: this is  part of devops
**Which solution do you suggest?**  
devspace.yaml:
```
deployments:
       - deplotment:  tradeservice        # a remote cluster service deployment  name in using namespace
images:
           $tagimage  // export  build image name
dev:
    images:
    cmd:
      - deploy="jd-gorouteproxy"
      - namespace="192-168-1-111"
      - kubectl set image deployment/$deploy $deploy=$tagimage -n $namespace
```
Deployment can  retrive from remote clusters.

**Comment by lizardruss** [comment]
Hello! This should already be possible with DevSpace. Most of our examples include a helm chart or manifests since that's the most common usage, however you can still target a deployment that was created elsewhere.

Here is an [example project](https://github.com/lizardruss/devspace-debug/tree/ci-deploy-example) to illustrate. You can simply omit the `deployments` configuration. As long as your deployment is found using `imageSelector` or `labelSelector`, the `devspace dev` should work.

You can also omit `images` if you have a shared `devImage` that is built using CI. Hope that helps!

**Comment by fengyeall111** [comment]
> Hello! This should already be possible with DevSpace. Most of our examples include a helm chart or manifests since that's the most common usage, however you can still target a deployment that was created elsewhere.
> 
> Here is an [example project](https://github.com/lizardruss/devspace-debug/tree/ci-deploy-example) to illustrate. You can simply omit the `deployments` configuration. As long as your deployment is found using `imageSelector` or `labelSelector`, the `devspace dev` should work.
> 
> You can also omit `images` if you have a shared `devImage` that is built using CI. Hope that helps!

Not only about devMode, when using devspace deploy,we can deploy like this:
```
deploy:
     - labelselector:  tradeservice        # a remote cluster service deployment  name in using namespace
     - imageselector: ""
```
So, we can build image in our local machine and directly replace  the container image. when using deployMode.

**Comment by lizardruss** [comment]
You can also do this with a pipeline, for example:
```yaml
images:
  app:
    image: app-local

pipelines:
  deploy-replace:
    flags:
      - name: deployment
        type: string
        default: ci
    run: |
      build_images app
      
      deployment=$(get_flag "deployment")
      image=$(get_image app)
      
      kubectl set image deployment/${deployment} test=${image} -n $DEVSPACE_NAMESPACE
```

You would then run this with the command:
```shell
devspace run-pipeline deploy-replace
```

I add the flag with a default value of `ci`, because that's what I called the deployment in the example repository. To override on the as needed, run:
```shell
devspace run-pipeline deploy-replace --deployment tradeservice
```

**Comment by someview** [comment]
> You can also do this with a pipeline, for example:
> 
> ```yaml
> images:
>   app:
>     image: app-local
> 
> pipelines:
>   deploy-replace:
>     flags:
>       - name: deployment
>         type: string
>         default: ci
>     run: |
>       build_images app
>       
>       deployment=$(get_flag "deployment")
>       image=$(get_image app)
>       
>       kubectl set image deployment/${deployment} test=${image} -n $DEVSPACE_NAMESPACE
> ```
> 
> You would then run this with the command:
> 
> ```shell
> devspace run-pipeline deploy-replace
> ```
> 
> I add the flag with a default value of `ci`, because that's what I called the deployment in the example repository. To override as needed, run:
> 
> ```shell
> devspace run-pipeline deploy-replace --deployment tradeservice
> ```


```
go mod tidy
go build -ldflags -s -ldflags -w -o main ./cmd/main/main.go 

project="tl.goprivate"
time=$(date "+%m%d%H%M")
tagimage="harbor.dev.wiqun.com:8443/go-test/$project:test$time"

docker login harbor.dev.wiqun.com:8443 -u user -p password
docker build -t $tagimage  .
docker push $tagimage
echo "image:$tagimage"

deploy="jd-goprivate"
namespace="192-168-1-217"
kubectl set image deployment/$deploy $deploy=$tagimage -n $namespace
namespace="192-168-1-239"
kubectl set image deployment/$deploy $deploy=$tagimage -n $namespace
```

docker logout harbor.dev.wiqun.com:8443
rm -rf main
// dockerfile
```
FROM alpine:3.14
WORKDIR /app
COPY main .
RUN echo "123"
ENTRYPOINT [ "./main" ]
```
Now we do the thing like this, how can we simplify the process by devspace and manage some projects

**Comment by lizardruss** [comment]
Hello! Apologies for the slow reply. It looks like you want to build the binary outside of the docker image, which should work as well. There's also a different approach that can be used for DevSpace that may be a better experience. I'll share an example and see if you want to try it.

The Docker login & logout are steps I'd recommend to do as needed, independently of DevSpace. DevSpace assumes that you're already authenticated to a registry before running it.

I tried to adapt your script to DevSpace as closely as possible, but added in recompilng & restarting the container when there are changes to the source code. Here's an example `devspace.yaml` with an explanation following:

**devspace.yaml**
```yaml
version: v2beta1

vars:
  PROJECT: tl.goprivate
  TIME: $(date "+%m%d%H%M")

images:
  project:
    image: harbor.dev.wiqun.com:8443/go-test/${PROJECT}
    tags:
    - test${TIME}

pipelines:
  dev: |-
    run_pipelines recompile-app default-dev
  recompile-app: |-
    run_watch --path ./cmd/** --path ./pkg/** -- ./hack/build.sh
  default-dev: |-
    run_default_pipeline dev
  default-deploy: |-
    run_default_pipeline deploy

dev:
  deploy1:
    namespace: "192-168-1-217"
    labelSelector:
      label: value # adjust to match your deployment / pods
    devImage: image(project)
    container: jd-goprivate
    workingDir: /app
    command:
    - ./main
    sync:
    - path: main
      file: true
      onUpload:
        restartContainer: true
  deploy1:
    namespace: "192-168-1-239"
    labelSelector:
      label: value # adjust to match your deployment / pods
    devImage: image(project)
    container: jd-goprivate
    workingDir: /app
    command:
    - ./main
    sync:
    - path: main
      file: true
      onUpload:
        restartContainer: true
```

**/hack/build.sh**
```shell
go mod tidy
go build -ldflags -s -ldflags -w -o main ./cmd/main/main.go
```

Running `devspace dev` will run the `dev` pipeline. I've configured it to run two parallel pipelines. `recompile-app` starts watching files at the paths `./cmd/**/*.go` and `./pkg/**/*.go` and re-runs the script to build your binary when there are changes. The `default-dev` pipeline runs the built-in default dev pipeline, which will build your image, tag it, and push it to the registry. This will also start the configuration under `dev`.

The `dev` section is configured to match the deployments via a `labelSelector` and replace the `jd-goprivate` container image with the image built (`harbor.dev.wiqun.com:8443/go-test/${PROJECT}`). You can also match using an [imageSelector](https://www.devspace.sh/docs/configuration/dev/selectors/image) if you know the image that's deployed ahead of time. There's two configurations since your script had two namespaces in the example.

File syncing is also configured to copy the compiled binary to the container at `/app/main` whenever it changes. When that file is uploaded, DevSpace will restart the `/app/main` binary without restarting the container. This will skip the need to re-pull the image each time, so you may be able to remove the ${TIME} variable from your image tag.

The end result will be similar to hot reloading the binary without the full image / build / push / pull / restart container cycle. The example may need some adjusting for your environment. Hope this was helpful!
