### ISSUE TITLE
The server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by afreyermuth98** [devspace-sh/devspace#2683]
**What happened?**
When I do a `devspace deploy` I got the follow error :

```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

I tried to deploy my charts using helm AND kubectl and I get the same error even if I have no problem with another equivalent project (almost a copy paste)

**What did you expect to happen instead?**
This is my second devspace project so I expect to get the same behaviour which is just working and deploying my app.

**How can we reproduce the bug?** (as minimally and precisely as possible)

My devspace.yaml:

```
version: v2beta1
name: docker-compose

localRegistry:
  enabled: false

deployments:
  app:
    kubectl:
      manifests:
        - .devspace/deployment.yaml
```

my .devspace/deployment.yaml :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        imagePullPolicy: Always
```

**Local Environment:**

* DevSpace Version: 6.3.2
* Operating System: mac
* ARCH of the OS: ARM64
  **Kubernetes Cluster:**
* Cloud Provider: aws
* Kubernetes Version: 1.25.7

**Anything else we need to know?**
