### ISSUE TITLE
Devspace purge all my deployments

### ISSUE THREAD

**Issue by afreyermuth98** [devspace-sh/devspace#2689]
**What happened?**  
I have two deployments called app1 and app2 and I want to purge only 1 of these two.
When I do `devspace purge` it purges my 2 deployments

Moreover, when I make two deployments with 2 different `devspace.yml`, I can't get the two deployments with `devspace list` but `devspace purge` still purge the two.

**What did you expect to happen instead?**  
I want to have the possibility to purge only 1 of the two, for example `devspace purge app1`

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Deploy 2 apps

My devspace.yaml:
```
version: ...
...
```

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: aws

**Anything else we need to know?**

**Comment by lizardruss** [comment]
Hello!

The default behavior for DevSpace is to deploy. / purge all applications under `deployments` in the devspace.yaml. This behavior is defined with the default [purge pipeline](https://www.devspace.sh/docs/configuration/pipelines/#purge).

You can customize this with a flag if you'd like:
```yaml
version: v2beta1

pipelines:
  purge:
    flags:
      - name: app
        type: string
        description: The app to purge
        short: a
    run: |-
      app=$(get_flag "app")
      
      stop_dev --all
      if [[ $app == "" ]]; then
        echo "Purge all deployments"
        purge_deployments --all
      else
        echo "Purge ${app}"
        purge_deployments $app
      fi
```

> Moreover, when I make two deployments with 2 different devspace.yml, I can't get the two deployments with devspace list but devspace purge still purge the two.

It's not clear to me why the separate `devspace.yml` would clear both, but they may be sharing the same `.devspace` folder, in which case the cache might be causing both to be purged. If you can share more details that would be helpful. A common pattern is to have each apps in separate folders, so each folder has a separate `devspace.yaml` and `.devspace` folder.
