### ISSUE TITLE
Create-react-app infinite restart 

### ISSUE THREAD

**Issue by RaduGabor** [devspace-sh/devspace#2690]
**What happened?**  

I have a create-react-app and when starting devspace dev the container is restarting without waiting to finish up starting.

**What did you expect to happen instead?**  

Waiting to start.

My devspace.yaml:
```
version: v2beta1
name: texodoc-client

deployments:
  texodoc-client:
    helm:
      values:
        containers:
          - image: node:16.13.2
            name: texodoc-client-container
            volumeMounts:
              - containerPath: /app
                volume:
                  name: volume-1
                  readOnly: false
        service:
          ports:
            - containerPort: 3000
              port: 3000
              protocol: TCP
        volumes:
          - name: app-client-1
            size: 5Gi
          - emptyDir: {}
            name: volume-1
        env:
          - name: NODE_ENV
            value: development
          - name: SKIP_PREFLIGHT_CHECK
            value: "true"
          - name: GENERATE_SOURCEMAP
            value: "true"
dev:
  texodoc-client:
    workingDir: /app
    labelSelector:
      app.kubernetes.io/component: texodoc-client
    command: ["npm"]
    args: ["run", "start"]
    sync:
      - path: ./:/app
        startContainer: true
        printLogs: true
        disableDownload: true
        excludePaths:
          - node_modules/
        onUpload:
            exec:
            - command: "npm install"
              once: true
            - command: "npm install"
              onChange: ["package.json"]
    ports:
      - port: 3000:3000
    logs:
      enabled: true
      lastLines: 10
    resources:
      limits:
        memory: 4Gi
```

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System: windows
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: other
- Kubernetes Version: 1.27.2

**Logs from devspace**
```
C:\Codebase\texodoc\client>devspace dev   
info Using namespace 'dev-texo-rg'
info Using kube context 'kube-timetree'
deploy:texodoc-client Deploying chart C:\Users\radug\.devspace\component-chart\component-chart-0.8.6.tgz (texodoc-client) with helm...
deploy:texodoc-client Deployed helm chart (Release revision: 1)
deploy:texodoc-client Successfully deployed texodoc-client with helm
dev:texodoc-client Waiting for pod to become ready...
dev:texodoc-client Selected pod texodoc-client-devspace-7c4f965cfc-bzp9w
dev:texodoc-client ports Port forwarding started on: 3000 -> 3000
dev:texodoc-client sync  Inject devspacehelper...
dev:texodoc-client sync  Start syncing
dev:texodoc-client sync  Sync started on: ./ <-> /app
dev:texodoc-client sync  Waiting for initial sync to complete
dev:texodoc-client sync  Downstream - Initial sync completed
dev:texodoc-client sync  Upstream - Upload 239 create change(s) (Uncompressed ~8680.03 KB)
dev:texodoc-client sync  Upstream - Successfully processed 239 change(s)
dev:texodoc-client sync  Upstream - Execute command 'npm install'
dev:texodoc-client sync  Upstream - Done executing command
dev:texodoc-client sync  Upstream - Execute command 'npm install', because 'package.json' changed
dev:texodoc-client sync  Upstream - Done executing command
dev:texodoc-client sync  Upstream - Initial sync completed
dev:texodoc-client sync  Initial sync completed
dev:texodoc-client logs  Streaming logs of pod:container texodoc-client-devspace-7c4f965cfc-bzp9w:texodoc-client-container
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  (Still waiting...)
dev:texodoc-client logs  Starting application...
dev:texodoc-client logs  
dev:texodoc-client logs  > texodoc-client@3.1.0 start
dev:texodoc-client logs  > react-scripts --max_old_space_size=4096 --trace-sigint --trace-exit --report-on-fatalerror start
dev:texodoc-client logs  
dev:texodoc-client logs  ℹ ｢wds｣: Project is running at http://10.1.139.170/
dev:texodoc-client logs  ℹ ｢wds｣: webpack output is served from
dev:texodoc-client logs  ℹ ｢wds｣: Content not from webpack is served from /app/public
dev:texodoc-client logs  ℹ ｢wds｣: 404s will fallback to /
dev:texodoc-client logs  Starting the development server...
dev:texodoc-client logs  
dev:texodoc-client logs  (node:230) WARNING: Exited the environment with code 0
dev:texodoc-client logs      at exit (node:internal/process/per_thread:189:13)
dev:texodoc-client logs      at /app/node_modules/react-scripts/scripts/start.js:172:17
dev:texodoc-client logs      at emit (node:events:390:28)
dev:texodoc-client logs      at endReadableNT (node:internal/streams/readable:1343:12)
dev:texodoc-client logs      at processTicksAndRejections (node:internal/process/task_queues:83:21)
dev:texodoc-client logs  
dev:texodoc-client logs  Container exited. Will restart in 7 seconds...
dev:texodoc-client logs  
dev:texodoc-client logs  
dev:texodoc-client logs  ############### Restart container ###############
dev:texodoc-client logs  
dev:texodoc-client logs  
dev:texodoc-client logs  > texodoc-client@3.1.0 start
dev:texodoc-client logs  > react-scripts --max_old_space_size=4096 --trace-sigint --trace-exit --report-on-fatalerror start
dev:texodoc-client logs  
dev:texodoc-client logs  ℹ ｢wds｣: Project is running at http://10.1.139.170/
dev:texodoc-client logs  ℹ ｢wds｣: webpack output is served from
dev:texodoc-client logs  ℹ ｢wds｣: Content not from webpack is served from /app/public
dev:texodoc-client logs  ℹ ｢wds｣: 404s will fallback to /
dev:texodoc-client logs  Starting the development server...
dev:texodoc-client logs  
dev:texodoc-client logs  (node:270) WARNING: Exited the environment with code 0
dev:texodoc-client logs      at exit (node:internal/process/per_thread:189:13)
dev:texodoc-client logs      at /app/node_modules/react-scripts/scripts/start.js:172:17
dev:texodoc-client logs      at emit (node:events:390:28)
dev:texodoc-client logs      at endReadableNT (node:internal/streams/readable:1343:12)
dev:texodoc-client logs      at processTicksAndRejections (node:internal/process/task_queues:83:21)
dev:texodoc-client logs  
dev:texodoc-client logs  Container exited. Will restart in 7 seconds...
```

**Anything else we need to know?**  

- I didn't eject my app
- If i exec into pod and run manually npm start, is working
