### ISSUE TITLE
`cat` command in config expressions does not preserve newlines

### ISSUE THREAD

**Issue by lizardruss** [devspace-sh/devspace#2691]
**What happened?**  
While attempting to externalize pipeline scripts, the following technique was attempted:
`devspace.yaml`
```yaml
version: v2beta1

name: cat-test

pipelines:
  dev:
    run: |-
      $(cat dev.sh)
```

`dev.sh`
```shell
echo "Hello"
echo "World"
```

However, when run it seems the script was not interpreted as expected when running `devspace dev`:
```
info Using namespace 'default'
info Using kube context 'minikube'
"Hello" echo "World"
```

**What did you expect to happen instead?**  
With the same configuration as above, I expected the output to be:
```
info Using namespace 'default'
info Using kube context 'minikube'
Hello
World
```

**Local Environment:**  
- DevSpace Version: DevSpace version : 6.3.2
- Operating System: mac
- ARCH of the OS: ARM64

**Comment by lizardruss** [comment]
Allowing this may break existing functionality, where expressions can be used inside of normal pipeline code. For example:
```yaml
pipelines:
  dev: |-
    build_images -t $(cat tag.txt)
```
