### ISSUE TITLE
Load pipelines from local files

### ISSUE THREAD

**Issue by lizardruss** [devspace-sh/devspace#2692]
**Is your feature request related to a problem?**  
Running shellcheck on pipeline code is currently not possible or cumbersome.

**Which solution do you suggest?**  
Adding the ability to define pipeline code in external files would enable easier linting. An example might look like:
```yaml
version: v2beta1
name: "pipeline-from-file"

pipelines:
  dev:
    script: dev.sh
```

This script would then be loaded from the local file system and run in the interpreted DevSpace shell environment.

**Which alternative solutions exist?**  
A possible alternative would be to load the contents of a local file using `cat`, however this is not currently working. For example:
```yaml
version: v2beta1
name: "pipeline-from-file"

pipelines:
  dev:
    run: $(cat dev.sh)
```

**Additional context**  
Separate issue #2691 created for allowing files to be included via config expressions instead.
