### ISSUE TITLE
Dev Pipeline Keeps SSH-ing

### ISSUE THREAD

**Issue by WaelKarkoub** [devspace-sh/devspace#2693]
**What happened?**  
`devspace dev` keeps sshing into the pod even when  `ssh.enabled` is set to false.

**What did you expect to happen instead?**  
It should only try to sync the files, without sshing into the pod at the end.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Any example should work, just disable ssh in `devspace.yaml`

My devspace.yaml:
```yaml
version: v2beta1
name: some_name

  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 4. Start dev mode "app" (see "dev" section)

  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

vars:
  USERNAME:
    source: env
    default: dev

images:
  app:
    image: some_image
    dockerfile: path/to/Dockerfile
    context: .

deployments:
  app:
    helm:
      chart:
        name: app/
      values:
        user: ${USERNAME}
        image:
          tag: ${runtime.images.app.tag}

dev:
  app:
    # Search for the container that runs this image
    terminal:
      disableReplace: true
    labelSelector:
      app: app-name
      user: ${USERNAME}
    sync:
      - path: ./
        excludeFile: .gitignore
    ssh:
      enabled: false
    proxyCommands:
      - gitCredentials: true
    ports:
      - port: "3000"

commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'
```

**Local Environment:**  
- DevSpace Version: `DevSpace version : 6.3.2`
- Operating System: Linux - Fedora 38
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
- K3D
- Kubernetes Version: 
```
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.26.1+k3s1
``` 

**Anything else we need to know?**
