### ISSUE TITLE
[Feature Request] Make it possible to enable/disable a dev sync

### ISSUE THREAD

**Issue by karbowiak** [devspace-sh/devspace#2718]
Hello, i am back with yet another feature request 😅 

Would it be possible to add an enable field to sync, so they can be turned on/off based on a var in Devspace. ?

Example:
```yaml
  sync-composer
    imageSelector: some.image.com/docker/composer
    sync:
      - path: vendor/
        initialSync: preferLocal
        waitInitialSync: true
        enable: $( [ "${ENABLE_COMPOSER_SYNC}" == "true" ] && echo true || echo false )
```

Could be higher level as well i guess..

```yaml
  development-main:
    imageSelector: some.image.com/docker/application
    enable: $( [ "${ENABLE_DEVELOPMENT}" == "true" ] && echo true || echo false )
    sync:
      - path: .:.
        excludePaths:
          - .git/
          - node_modules/
        onUpload: {}
        initialSync: preferLocal
        waitInitialSync: true
    proxyCommands:
      - gitCredentials: true
    restartHelper:
      inject: false
    reversePorts:
      - port: 9000:9000
```

To enable/disable an entire block programatically, where default would always be true..

(Also sorry if this isn't a feature request, i did scour the documentation and source to see if this already existed, but couldn't find anything 😅)

Reason for the feature request is that, the setup I've built is now kinda running away from me, with the same files being used for multiple variations of the development environment, where some people want to use Redis, and some don't - and in my case i need to have multiple dev.yaml files with/without redis sync enabled.
And mongodb, and elasticsearch, etc.

And for each one they multiply. 😂

**Comment by lizardruss** [comment]
Hello! This is one of the intended use cases behind [pipelines](https://www.devspace.sh/docs/configuration/pipelines/). They enable you to define most of the `dev` behavior in declarative configuration, but also programmatically enable / disable which ones are run. Here's an example based on yours:
```yaml
version: v2beta1
pipelines:
  dev: |-
    # Default dev pipeline
    run_dependencies --all
    ensure_pull_secrets --all
    build_images --all
    create_deployments --all

    # Customize start_dev based on variables
    deployments=()

    if is_equal ${ENABLE_COMPOSER_SYNC} "true"; then
      deployments+=("sync-composer")
    fi
    
    if is_equal ${ENABLE_DEVELOPMENT} "true"; then
      deployments+=("development-main")
    fi

    start_dev "${deployments[@]}"
dev:
  sync-composer:
    imageSelector: some.image.com/docker/composer
    sync:
      - path: vendor/
        initialSync: preferLocal
        waitInitialSync: true
  development-main:
    imageSelector: some.image.com/docker/application
    sync:
      - path: .:.
        excludePaths:
          - .git/
          - node_modules/
        onUpload: {}
        initialSync: preferLocal
        waitInitialSync: true
    proxyCommands:
      - gitCredentials: true
    restartHelper:
      inject: false
    reversePorts:
      - port: 9000:9000
```

There are also [pipeline flags](https://www.devspace.sh/docs/configuration/pipelines/?x0=2#custom-flags) that can be used for a similar purpose, or you can define your own pipelines if you have fixed groups of applications that are always run together.
