### ISSUE TITLE
Purge all helm release without knowing releaseName

### ISSUE THREAD

**Issue by afreyermuth98** [devspace-sh/devspace#2720]
**What happened?**  

I'm releasing some stuff using the helm releaseName like this
```
deployments:
  app:
    helm:
      chart:
        name: my-chart-name-${SOME_RELEASE_NAME}
      releaseName: ${SOME_RELEASE_NAME}
```

Then I want to purge this release but I cannot access the previous `SOME_RELEASE_NAME` value.

**What did you expect to happen instead?**  

Have something to be able to purge the release even without knowing its name.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Release an helm chart with a releaseName depending on a variable and then try to purge this release without this variable.

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.26.7

**Anything else we need to know?**

**Comment by lizardruss** [comment]
@afreyermuth98 Could you share your `devspace.yaml`? Here's a very simple example that works with `devspace deploy` & `devspace purge`. You might also check to see whether the namespace being used by devspace is the same that was used for the original deployment, since DevSpace uses a secret to cache the deployment information.

```yaml
version: v2beta1

deployments:
  app:
    helm:
      releaseName: release-${DEVSPACE_TIMESTAMP}
      values:
        containers:
          - image: alpine
            command:
              - sh
              - -c
              - sleep infinity
```
