### ISSUE TITLE
dockerignore is ignored

### ISSUE THREAD

**Issue by xgalaxy** [devspace-sh/devspace#2723]
**What happened?**  

`.dockerignore` file is being.. well.. ignored when doing `devspace deploy` :)

If a dockerfile contains the contents:

```
COPY . .
```

Files listed in the `.dockerignore` get copied into the image anyway. This also results in a needless cache invalidation of that image layer. [Which was reported in 2021 here](https://github.com/devspace-sh/devspace/issues/1388).

**What did you expect to happen instead?**  

The `.dockerignore` file should be respected when doing a deploy.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: playground

images:
  test:
    image: test
    buildKit: {}
    dockerfile: k8s/Dockerfile

deployments:
  test:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
```

My dockerfile:
```
# syntax=docker/dockerfile:1.4
FROM mcr.microsoft.com/devcontainers/go:1.20-bookworm AS develop
ENV GOMODCACHE=/cache/gomod
ENV GOCACHE=/cache/gobuild
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/cache/gomod \
    go mod download
RUN --mount=type=cache,target=/cache/gomod \
    --mount=type=cache,target=/cache/gobuild \
    CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/${SERVICE_NAME}

FROM gcr.io/distroless/base-debian11 AS production
COPY --from=build /app/main /
CMD ["/main"]
```

My .dockerignore
```
.git
.idea
k8s
devspace.yaml
```

**Local Environment:**  
- DevSpace Version: devspace version 6.3.3
- Operating System: WSL/Ubuntu
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

**Anything else we should know:**
Same setup transported to Tilt does not exhibit this behavior. So I don't think this is a docker/buildkit bug.
