### ISSUE TITLE
Help injecting image pull secrets into my deployment manifest.

### ISSUE THREAD

**Issue by matthewcummings** [devspace-sh/devspace#2725]
**What happened?**  
I cannot inject imagePullSecrets into my manifests/deployments via `devspacy.yml`

**What did you expect to happen instead?**  
I'm expecting this to be possible. I _think_ I can do something like this (I'm using Dockerhub):
```
pullSecrets:
  dockerhub:
    registry: docker.io
    secret: dockerhub
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  
In my deployment manifest, I'd expect to reference the above secret via:
```
      imagePullSecrets:
        - name: dockerhub
```
But the secret is not being created.

My devspace.yaml:
```
pullSecrets:
  dockerhub:
    registry: docker.io
    secret: dockerhub
```

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: linux (Ubuntu 22.04)
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
- Cloud Provider: k3d (local)
- Kubernetes Version: v1.26.7

**Anything else we need to know?**
