### ISSUE TITLE
Pipeline output is not displayed until a newline is reached

### ISSUE THREAD

**Issue by jackwilsdon** [devspace-sh/devspace#2743]
**What happened?**
Text printed from a pipeline is not output to the terminal until a newline is reached.

**What did you expect to happen instead?**  
Text should be printed without needing a newline.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

 1. Create this `devspace.yaml`:
    ```yaml
    version: v2beta1
    pipelines:
      test: |
        echo -n "Text without a newline"
        sleep 1
        echo "... finished!"
    ```
 2. Run `devspace run-pipeline test`
 3. Note that "Text without a newline" doesn't appear until "... finished!" is printed

**Local Environment:**  
- DevSpace Version: 6.3.3
- Operating System: macOS Sonoma 14.0
- ARCH of the OS: arm64

**Anything else we need to know?**  
This is a bigger issue when using `read -p "Some prompt here: "`, as the prompt doesn't appear until the user has hit enter (completing the `read`).
