### ISSUE TITLE
run_dependencies --sequential results in incorrect build order

### ISSUE THREAD

**Issue by jackwilsdon** [devspace-sh/devspace#2744]
**What happened?**  
With the following dependency graph:

![dependency graph](https://github.com/devspace-sh/devspace/assets/1843197/c7dffbcd-57ca-45b6-849e-9f7a090969e2)

If `devspace deploy` is run in project `a` which uses `run_dependencies --all --sequential`, it incorrectly marks `c` as already being deployed, leading to the incorrect deploy order `a` → `b` → `c`. 

**What did you expect to happen instead?**  
The build order should be `a` → `c` → `b`, as `b` depends on `c`.

**How can we reproduce the bug?** (as minimally and precisely as possible) 
 1. Create these three files:
    **a/devspace.yaml**
    ```yaml
    version: v2beta1
    name: a
    dependencies:
      b:
        path: ../b
      c:
        path: ../c
    pipelines:
      deploy: |
        echo "Deploying a..."
        run_dependencies --all --sequential
    ```
    **b/devspace.yaml**
    ```yaml
    version: v2beta1
    name: b
    dependencies:
      c:
        path: ../c
    pipelines:
      deploy: |
        echo "Deploying b..."
        run_dependencies --all
    ```
    **c/devspace.yaml**
    ```yaml
    version: v2beta1
    name: c
    pipelines:
      deploy: |
        echo "Deploying c..."
    ```
 2. Run `devspace deploy` inside `a`
 3. Note that the deploy order is incorrect:
    ```text
    Deploying a...
    b Deploying b...
    b Skipping dependency c as it was already deployed
    c Deploying c...
    ```

**Local Environment:**  
- DevSpace Version: 6.3.3
- Operating System: macOS Sonoma 14.0
- ARCH of the OS: arm64

**Anything else we need to know?**  
It's not clear if this is intended behaviour with the combination of `--all` and `--sequential`, as there isn't really an explicit order to dependencies in the configuration. Ideally it would resolve the ordering when using `--all` and `--sequential` or throw an error if the order can't be resolved.
