### ISSUE TITLE
Release name cannot be set using environment variable

### ISSUE THREAD

**Issue by kelly-brown** [devspace-sh/devspace#2751]
**What happened?**  
I suspect a bug regression.  I can not use a variable in my release name field but I believe this is supposed to work.

When running devspace dev

postgres deploy:postgres Deploying chart postgresql (postgres) with helm...
postgres create_deployments: error deploying postgres: unable to deploy helm chart:  error executing 'helm upgrade ${USER} --values /var/folders/s2/2ngzzp3s4znf500qz0yk2zxc0000gq/T/2543688261 --install --namespace mynamespace postgresql --repo https://charts.bitnami.com/bitnami --repository-config='' --version 13.1.0 --kube-context my-context': Error: release name is invalid: ${USER}

**What did you expect to happen instead?**  
It should resolve the environment variable and name my helm release that.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

Create a deployment like this

```
version: v2beta1

vars:
  USER: $(whoami)

deployments:
  postgres:
    helm:
      releaseName: ${USER}
      chart:
        name: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: "13.1.0"
      values:
```

**Local Environment:**  
- DevSpace Version: 6.3.3
- Operating System: mac
- ARCH of the OS: Intel
**Kubernetes Cluster:**  
- Cloud Provider: google
- Kubernetes Version: GKE v1.26.5-gke.210
