### ISSUE TITLE
server ports ignored when tcp/udp with component chart

### ISSUE THREAD

**Issue by withinboredom** [devspace-sh/devspace#2755]
**What happened?**  
Created a service on a component chart deployment:

```
        service:
          name: web
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: 80
              protocol: TCP
              name: http
            - port: 443
              targetPort: 443
              protocol: TCP
              name: https-legacy
            - port: 443
              targetPort: 443
              protocol: UDP
              name: https3
```

**What did you expect to happen instead?**  

A service with both UDP & TCP 443 open (to support h3/quic). Instead, a service with TCP-only is created.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`]
- Operating System: windows | linux | mac
- ARCH of the OS: AMD64 | ARM64 | i386
**Kubernetes Cluster:**  
- Cloud Provider: google | aws | azure | other
- Kubernetes Version: [use `kubectl version`]

**Anything else we need to know?**
