### ISSUE TITLE
Runtime variables mangled by config expression

### ISSUE THREAD

**Issue by jackwilsdon** [devspace-sh/devspace#2760]
**What happened?**  
I wrote a config expression which output the name of a runtime variable (to be used by DevSpace after the config expression is evaluated), but the name of the variable was mangled.

**What did you expect to happen instead?**  
The name of the variable to not be mangled.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

1. Create the following `devspace.yaml`:
   ```yaml
   version: v2beta1
   name: test
   dev: |
     $(cat <<EOF
     test:
       imageSelector: \${runtime.images.test}
     test-ok:
       imageSelector: \${runtime.images.test-ok}
     EOF)
   images:
     test:
       image: hello-world-1
     test-ok:
       image: hello-world-2
   ```
2. Run `devspace print`
3. Note that the `runtime.images.test` variable is mangled in the output (also impacting runtime):
   ```yaml  
   version: v2beta1
   name: test
   images:
       test:
           image: hello-world-1
       test-ok:
           image: hello-world-2
   dev:
       test:
           imageSelector: ${runtime___devspace___images___devspace___test}
       test-ok:
           imageSelector: ${runtime.images.test-ok}
   ```

**Anything else we need to know?**  
It looks like this is caused by the code which makes variable names "valid" shell syntax:
https://github.com/devspace-sh/devspace/blob/6c1e41e994785543e16e3d39a27c64de286bff29/pkg/devspace/pipeline/engine/engine.go#L45-L53

The reason that the issue doesn't affect `test-ok` is that the regular expression does not match variables containing a `-`: https://github.com/devspace-sh/devspace/blob/6c1e41e994785543e16e3d39a27c64de286bff29/pkg/devspace/pipeline/engine/engine.go#L17

Should this replacement be applied during config expression evaluation? It seems like the `runtime.` variables aren't available at this point anyway (as the config is still being evaluated).

**Comment by jackwilsdon** [comment]
I've worked around this for now by doing this:
```yaml
version: v2beta1
name: test
dev: |
  $(
    var() { echo "\${$1}"; }
    cat <<EOF
  test:
    imageSelector: $(var runtime.images.test)
  test-ok:
    imageSelector: $(var runtime.images.test-ok)
  EOF
  )
images:
  test:
    image: hello-world-1
  test-ok:
    image: hello-world-2
```

**Comment by lizardruss** [comment]
@jackwilsdon Hello! Here's another way of escaping the expression that might be a little easier:

```yaml
version: v2beta1
name: test
dev: |
  $(cat <<EOF
  test:
    imageSelector: \$'{runtime.images.test}'
  test-ok:
    imageSelector: \$'{runtime.images.test-ok}'
  EOF)
images:
  test:
    image: hello-world-1
  test-ok:
    image: hello-world-2
```

You might also look into using a pipeline instead of config expressions. For dynamic `dev` config you can use [`--set`](https://www.devspace.sh/docs/configuration/pipelines/?x0=2#start_dev-set) to override specific fields. The above works too, but sometimes it's difficult to get everything interpreted by variables / config expressions to work together nicely.
