### ISSUE TITLE
Devspace deploy do not git pull for cached dependencies

### ISSUE THREAD

**Issue by Andrioden** [devspace-sh/devspace#2765]
**What happened?**  
As part of this PR https://github.com/devspace-sh/devspace/pull/2709 i introduced a regression bug where it now never attempts to `git pull` for cached dependencies.

I have created a PR https://github.com/devspace-sh/devspace/pull/2766 to revert this with some refactoring.

**What did you expect to happen instead?**  
Given the configuration

``` yaml
dependencies:
  dependency-a:
    git: https://www.somewhere.com/dependency-a
    branch: master
    disablePull: false
```

I expect devspace deploy to pull new commits to dependency-a that has happen since the last devspace deploy.

**Local Environment:**  
- DevSpace Version: 6.3.5
- Operating System: windows 
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: kind
- Kubernetes Version: 1.27.2

**Anything else we need to know?**  
Read https://github.com/devspace-sh/devspace/pull/2766
