### ISSUE TITLE
Devspace deploy unnecessarily download ignored dependencies

### ISSUE THREAD

**Issue by Andrioden** [devspace-sh/devspace#2767]
**What happened?**  
Running `devspace deploy` downloads the dependencies of a ignored dependency's.

**What did you expect to happen instead?**  
Skip downloading ignore dependency's dependencies.

**How can we reproduce the bug?**

Parent devspace.yaml:
```
name: parent
dependencies:
  child-a:
    git: ...
    branch: master
    ignoreDependencies: true
```

Child devspace.yaml:
```
name: child-a
dependencies:
  child-b:
    git: ...
    branch: master
```

Add a log.Debugf to DownloadDependency method

-> 

Observe that the DownloadDependency is called like thid:
```
Download parent
Download child-a
Download child-b <- Unecessary
```

**Local Environment:**  
- DevSpace Version: 6.3.5
- Operating System: windows 
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: kind
- Kubernetes Version: 1.27.2
