### ISSUE TITLE
False alarms due to devspace-schema.json

### ISSUE THREAD

**Issue by alexrimlin** [devspace-sh/devspace#2770]
**What happened?**  
Using expressions or variables in `.image` results in warnings in IDE because of `devspace-schema.json`.

**What did you expect to happen instead?**  
Would be nice to get rid of these false alarms.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: foo

images:
  app:
    image: ${CI_REGISTRY_IMAGE}:${POSTFIX}
    appendDockerfileInstructions: ${APPEND_DOCKERFILE_INSTRUCTIONS}
    kaniko:
      cache: true
      snapshotMode: redo
      image: gcr.io/kaniko-project/executor:v1.18.0
      tolerations: &tolerations $(cat components.yaml | yq -r .tolerations)
      nodeSelector: &nodeSelector $(cat components.yaml | yq -r .nodeSelector)
```
<img width="581" alt="image" src="https://github.com/devspace-sh/devspace/assets/63896744/3bd5cc19-5475-4909-af5a-3520a06d3fa8">

**Local Environment:**  
- DevSpace Version: 6.3.4
- Operating System: mac
- ARCH of the OS: ARM64
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: v1.28.3
