### ISSUE TITLE
Devspace import from git does not pick up changes to remote config repository

### ISSUE THREAD

**Issue by djfinnoy** [devspace-sh/devspace#2772]
**What happened?**
When storing devspace functions in a github repository, and loading them via `imports`, devspace seems to cache the resulting config, and ignores changes to the remote config repository.

**What did you expect to happen instead?**
Assume:

```
imports:
  - git: https://github.com/org/devspace-config
    branch: dev
    subPath: ./functions
```

When pushing changes to this repository, I would expect to see those changes through the output of `devspace print`.
Instead, it seems like the remote functions are only fetched once, and all changes are ignored.
At the moment, I can only get function changes implemented by changing the target branch name of org/devspace-config.

**How can we reproduce the bug?** (as minimally and precisely as possible)

Import remote config from a branch, run `devspace print`, make  changes to the config branch, and run `devspace print` again.
My devspace.yaml:

```
version: 6.3.7
```

**Comment by HKablan** [comment]
I have the same problem also - the changes from git are not loaded..

**Comment by djfinnoy** [comment]
You have to delete the local cache, I believe it's under `~/.devspace`. Would be nice if there was an easier way to refresh a remote source though.

**Comment by FabianKramm** [comment]
@djfinnoy thanks for creating this issue! Mhh strange, DevSpace should run a pull automatically, would you mind trying with:
```yaml
imports:
  - git: https://github.com/org/devspace-config
    branch: dev
    subPath: ./functions
    disableShallow: true
```
