### ISSUE TITLE
Persistent paths not mounted when using multiple containers

### ISSUE THREAD

**Issue by maartendeprez** [devspace-sh/devspace#2782]
**What happened?**  

When using multiple containers, `devspace dev` will create the persistent volume, but fails to mount it on the dev containers. Both the `volumes` and `volumeMounts` entries are missing from the pathed pod spec.

**What did you expect to happen instead?**  

Persistent paths are mounted in the dev container.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
dev:
  mypod:
    # ...
    containers:
      mycontainer1:
        # ...
        persistPaths:
          - path: /my/persistent/path
      mycontainer2:
        # ...
        persistPaths:
          - path: /my/other/persistent/path
```

**Local Environment:**  
- DevSpace Version: 6.3.8
- Operating System: linux
- ARCH of the OS: AMD64

**Kubernetes Cluster:**  
- Kubernetes Version: v1.26.3+k3s1

**Anything else we need to know?**
