### ISSUE TITLE
Endless wait loop when using multiple containers with delayed start

### ISSUE THREAD

**Issue by maartendeprez** [devspace-sh/devspace#2783]
**What happened?**  

When using pods with multiple containers and `startContainer: true` sync paths, all containers except one enter an infinite wait loop on startup. The dev pod is set up and the logs report `Initial sync completed`, but all containers except one keep spewing `(Still waiting...)` messages.

**What did you expect to happen instead?**  

All containers start after initial sync is completed.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
dev:
  mypod:
    # ...
    containers:
      container1:
        # ...
        sync:
          - path: .:/my/synced/path
            startContainer: true
      container2:
        # ...
        sync:
          - path: .:/my/synced/path
            startContainer: true
```

**Local Environment:**  
- DevSpace Version: 6.3.8
- Operating System: linux
- ARCH of the OS: AMD64

**Kubernetes Cluster:**  
- Kubernetes Version: v1.26.3+k3s1

**Anything else we need to know?**
