### ISSUE TITLE
Helper restart does not give container process the chance to shut down properly

### ISSUE THREAD

**Issue by maartendeprez** [devspace-sh/devspace#2788]
**What happened?**  

When my container is restarted due to sync.onUpload.restartContainer, the container process is (almost) immediately killed. In my case, this prevents the watcher from cleaning up the subprocess running in another process group.

**What did you expect to happen instead?**  

The restart helper should send SIGINT, SIGTERM and finally SIGKILL, with some time in-between the signals.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
dev:
  mypod:
    # ...
    sync:
      - path: .:.
        onUpload:
          restartContainer: true
```

**Local Environment:**  
- DevSpace Version: 6.3.8
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Kubernetes Version: v1.26.3+k3s1

**Anything else we need to know?**
