### ISSUE TITLE
Updating Statefulset fails

### ISSUE THREAD

**Issue by CKnoppas** [devspace-sh/devspace#2907]
We created sts with devspace 6.3.2. When updating the statefulset with devspace 6.3.3 or current (6.3.14) the sts patching fails.
https://github.com/devspace-sh/devspace/compare/v6.3.2...v6.3.3

`
timescale Error: UPGRADE FAILED: cannot patch "timescale" with kind StatefulSet: StatefulSet.apps "timescale" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
`

**What did you expect to happen instead?**  
devspace deploy the sts yaml without errors - specs of sts did not change

**How can we reproduce the bug?** (as minimally and precisely as possible)  

1. devspace deploy with the provided yaml and version [v6.3.2](https://github.com/devspace-sh/devspace/releases/tag/v6.3.2)
2. devspace deploy with the provided yaml and version [v6.3.3](https://github.com/devspace-sh/devspace/releases/tag/v6.3.3)

My devspace.yaml:
```
version: v2beta1

deployments:
  timescale:
    helm:
      values:
        securityContext:
          fsGroup: 70
        containers:
          - image: timescale/timescaledb:2.11.1-pg15
            env:
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_PASSWORD
                value: postgres
              - name: POSTGRES_DB
                value: postgres
              - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
            volumeMounts:
              - containerPath: /var/lib/postgresql/data
                volume:
                  name: db-data
                  subPath: /timescale-data
        volumes:
          - name: db-data
            size: 2Gi
            storageClassName: standard
        service:
          ports:
            - port: 5432
```

**Local Environment:**  
- DevSpace Version: 6.3.2 / 6.3.3 / 6.3.14
- Operating System:  linux 
- ARCH of the OS: AMD64
- Kubernetes: v1.30 with minikube 

**Anything else we need to know?**

as far as i can see the problem is the volumeClaimTemplates **helm.sh/chart annotation**. devspace tries to patch this to `helm.sh/chart: component-chart-0.9.0` which fails. see https://github.com/devspace-sh/devspace/pull/2632 

`volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        helm.sh/chart: component-chart-0.8.6
      creationTimestamp: null
`  

i would suggest to exclude the annotation from the the volumeClaimTemplate section. Otherwise all update of sts will fail when user upgraded to a devspace version where the component chart version was bumped. 

if you agree, i will be happy to provide a PR!

**Comment by zerbitx** [comment]
The `devspace.yaml` you shared is only setting the helm values, which results in `devspace` trying to use the [bundled component-chart](https://github.com/devspace-sh/devspace/blob/main/hack/build-all.bash#L69), and is working as intended, since the chart itself was upgraded with the command.  There are a couple of workarounds assuming you don't want to go back to an older version of `devspace`.

  1) Purge and redeploy: If you don't need to preserve the data in that particular deployment of timescale db, you can do a `devspace purge`, then `devspace dev` with the newer version to get going with the component-chart `0.9.1`.
  2) Use a local chart:  If you need to preserve that deployment and want to stick with `0.8.6` you can get the chart with `helm pull component-chart --repo https://charts.devspace.sh --version 0.8.6` then update your `devspace.yaml` to look like this:

```yaml
version: v2beta1

deployments:
  timescale:
    helm:
      chart:
        path: ./component-chart-0.8.6.tgz
      values:
        securityContext:
          fsGroup: 70
...
```
