### ISSUE TITLE
DEVSPACE_CONFIG is not honoured when used with git based dependencies

### ISSUE THREAD

**Issue by jaydeland** [devspace-sh/devspace#2919]
**What happened?**  
- I have DEVSPACE_CONFIG set to devspace-2.yaml and when my dependency is pulled in from git it still tries to use the devspace.yaml
- NOTE: This does work when using path based dependencies

**What did you expect to happen instead?**  
I expected devspace2.yaml to be used

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: app1

vars:
  service_name: ${DEPLOY_NAME}
  MYSQL_HOST: mysql
  MYSQL_DATABASE: ${DEVSPACE_NAME}_development
  MYSQL_PASSWORD: password
  MYSQL_USER: root

imports:
  - git: <REPO>
    subPath: devspace/app
    branch: main

dependencies:
  app-dep1:
    git: <REPO>
    branch: feature/devspace
  app-dep2:
    git: <REPO>
    branch: master
```

**Local Environment:**  
- DevSpace Version: devspace version 6.3.14
- Operating System: mac
- ARCH of the OS:ARM64

**Anything else we need to know?**
