### ISSUE TITLE
Really slow port forwarding connection

### ISSUE THREAD

**Issue by shinebayar-g** [devspace-sh/devspace#2934]
**What happened?**  
Really slow port forwarded connection

**What did you expect to happen instead?**  
Fast seamless connection

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:

```yaml
version: v2beta1
name: quickstart-nodejs

pipelines:
  dev:
    run: |-
      run_dependencies --all
      create_deployments --all
      start_dev --all

deployments:
  app:
    kubectl:
      manifests:
        - ./deployment.yaml

dev:
  app:
    namespace: dev
    labelSelector:
      app: astro-dev
    devImage: node:22.13-slim
    terminal: {}
    sync:
      - path: ./:/app
        excludeFile: .gitignore
    ports:
      - port: "4321:4321"

```

**Local Environment:**  
- DevSpace Version: 6.3.14
- Operating System: linux
- ARCH of the OS: AMD64
**Kubernetes Cluster:**  
- Cloud Provider: cloud provider - other
- Kubernetes Version: Server Version: v1.32.1

**Anything else we need to know?**  

To reproduce use the `deployment.yaml` and `devspace.yaml` file.
Create a new astro project with `pnpm create astro@latest`.
Run `devspace dev` and install pnpm with `npm i -g pnpm`
Start the astro project with `pnpm dev`
Connect to http://localhost:4321
Notice that connection is really really slow.

deployment.yaml file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-dev
  namespace: dev
  labels:
    app: astro-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astro-dev
  template:
    metadata:
      labels:
        app: astro-dev
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: node:22.13-slim
          imagePullPolicy: IfNotPresent
          name: astro-dev
```
