### ISSUE TITLE
[Bug] /require/* section does not merge on imports

### ISSUE THREAD

**Issue by timofey-drozhzhin** [devspace-sh/devspace#2935]
**What happened?**  
When [importing](https://www.devspace.sh/docs/configuration/imports/) like this
```
imports:
  - path: import.yaml
```
The entire `/require/*` section becomes overridden if it's redeclared.

**What did you expect to happen instead?**  
According to the [documentation](https://www.devspace.sh/docs/configuration/imports/#imports-vs-dependencies), sections are supposed to merge, not replace one another. And we can see that with functions, pipelines, etc... Likewise the `/require/*` section should merge commands, not replace the entire section when additional .require.commands.* are added.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

import.yaml
```
version: v2beta1
name: devspace

require:
  commands:
    - name: example
      version: "1"
```

devspace.yaml:
```
version: v2beta1
name: devspace
    
imports:
  - path: import.yaml

pipelines:
  demo:
    run: |-
      echo "The 'example' command is never checked"

require:
  commands:
    - name: devspace
      versionRegEx: "DevSpace version : (.+)"
      version: ">=6"
...
```

Run `devspace run-pipeline demo`

You will see that `.require.commands[name=example]` is never evaluated, as expected.

**Local Environment:**  
- DevSpace Version: 6.3.14
- Operating System: linux
- ARCH of the OS: arm64
**Kubernetes Cluster:**  
- Cloud Provider: n/a
- Kubernetes Version: n/a

**Anything else we need to know?**
