### ISSUE TITLE
Purge doesn't handle `profiles`

### ISSUE THREAD

**Issue by andrewhertog** [devspace-sh/devspace#2943]
**What happened?**  
I have a variable of type command which we override in profiles. This command doesn't exist in our CI environment so we override it and use a different command within a profile using a strategic merge.

We also run a `devspace purge` within the CI environment, but it is failing because it doesn't evaluate based on the profile we pass into it. 

**What did you expect to happen instead?**  
as the `profile` flag is a global flag, I would expect every command to handle it the same way. It appears that `devspace purge` does not.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
vars:
  MY_COMMAND_VAR: 
     source: command
     command: 'command that doesn't work'

profiles:
- name: test
   description: test profile
   merge:
      vars:
         MY_COMMAND_VAR:
            source: command
            command: 'command that works'
...
```

**Local Environment:**  
I've seen this on multiple environments
- DevSpace Version: 6.3.14, 6.3.13, 6.3.3
- Operating System: Mac, Linux
- ARCH of the OS: AMD64 and ARM64 
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: v1.30.9-eks-8cce635

**Anything else we need to know?**  
I've dug a bit into the source code and used copilot to confirm my suspicions.

**Comment by andrewhertog** [comment]
I've created a new project via `devspace init` and added the above snippet to it, and it appears to work as expected when running `devspace purge` and `devspace purge -p test`

However, I'm still having an issue in my actual project. I'm going to give an actual set of snippets to give more context on what we are working with.

devspace.yaml
```yaml
version: v2beta1

dependencies:
  client-event-publisher-dependencies:
    path: ./devspace/dependencies/devspace.yaml

imports:
  - path: ./devspace/commands.yaml
  - path: ./devspace/deployments.yaml
  - path: ./devspace/dev.yaml
  - path: ./devspace/images.yaml
  - path: ./devspace/profiles.yaml
  - path: ./devspace/variables.yaml
  - path: ./devspace/pipelines.yaml

```

./devspace/variables:yaml
```yaml
version: v2beta1
# https://www.devspace.sh/docs/configuration/variables
vars:
    CODEARTIFACT_AUTH_TOKEN:
        source: command
        command: 'foobar'
```

./devspace/profiles.yaml
```yaml
version: v2beta1
# https://www.devspace.sh/docs/configuration/profiles/
profiles:
 - name: preview
    description: "used to deploy preview environments"
    merge:
      vars:
        CODEARTIFACT_AUTH_TOKEN: 
          source: command
          command: 'aws codeartifact get-authorization-token --domain mydomain --domain-owner 111222333444 --query authorizationToken --output text'
```

When I change that command to almost anything else it seems to work fine.

```sh
❯ devspace purge -p preview
info Using namespace 'adenhertog'
info Using kube context 'sandbox'
fatal deploy dependencies: resolve dependencies: loading config for dependency client-event-publisher-dependencies: fill variable CODEARTIFACT_AUTH_TOKEN with command 'foobar': exit status 127

stderr:
"foobar": executable file not found in $PATH
```

```sh
❯ devspace purge
info Using namespace 'adenhertog'
info Using kube context 'sandbox'
fatal fill variable CODEARTIFACT_AUTH_TOKEN with command 'foobar': exit status 127

stderr:
"foobar": executable file not found in $PATH
```

Updating the profile variable to `command 'something'` 
```sh
❯ devspace purge -p preview
info Using namespace 'adenhertog'
info Using kube context 'sandbox'
fatal fill variable CODEARTIFACT_AUTH_TOKEN with command 'something': exit status 127

stderr:
"something": executable file not found in $PATH
```

**Comment by andrewhertog** [comment]
I've updated the dependency with the following:

```yaml
dependencies:
  client-event-publisher-dependencies:
    path: ./devspace/dependencies/devspace.yaml
    overwriteVars: true
```
and removed the import of `../variables.yaml` in the dependency and it seems to have resolved the issue
