### ISSUE TITLE
Error: Null Pointer Exception Occured

### ISSUE THREAD

**Issue by Klassikcat** [devspace-sh/devspace#2957]
**What happened?**  
Devspace has crashed when use `devspace {pipeline-name}` on windows 11. for example, using `devspace dev` results in: 

stacktrace:
```log
info Using namespace 'blackcircles-kt'
info Using kube context 'blackcircles_develop'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1f78672]

goroutine 87 [running]:
github.com/loft-sh/devspace/pkg/devspace/server.(*Server).ListenAndServe(...)
        /Users/runner/work/devspace/devspace/pkg/devspace/server/server.go:93
github.com/loft-sh/devspace/pkg/devspace/dev.UI.func1()
        /Users/runner/work/devspace/devspace/pkg/devspace/dev/dev.go:26 +0x12
created by github.com/loft-sh/devspace/pkg/devspace/dev.UI in goroutine 1
        /Users/runner/work/devspace/devspace/pkg/devspace/dev/dev.go:25 +0x1a7
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1fa4bb6]

goroutine 1 [running]:
github.com/loft-sh/devspace/cmd.runPipeline({0x2b96d90, 0xc00037f5f0}, {0x46d29e0, 0x0, 0x0}, 0xc000a0f7a0)
        /Users/runner/work/devspace/devspace/cmd/run_pipeline.go:466 +0xad6
github.com/loft-sh/devspace/cmd.(*RunPipelineCmd).Run.func1()
        /Users/runner/work/devspace/devspace/cmd/run_pipeline.go:242 +0x2b
github.com/loft-sh/devspace/pkg/util/interrupt.(*Handler).Run(0xc00025f8b0, 0xc000a0f910, 0xc000a52330)
        /Users/runner/work/devspace/devspace/pkg/util/interrupt/interrupt.go:114 +0x148
github.com/loft-sh/devspace/cmd.runWithHooks({0x2b96d90, 0xc00037f5f0}, {0x25fca2d, 0xa}, 0xc000a0f910)
        /Users/runner/work/devspace/devspace/cmd/run_pipeline.go:359 +0x1af
github.com/loft-sh/devspace/cmd.(*RunPipelineCmd).Run(0xc000834480, 0xc00089a308, {0x46d29e0?, 0x0?, 0x16304ea700000000?}, {0x2b92648, 0x46d29e0}, {0x25fca2d, 0xa})
        /Users/runner/work/devspace/devspace/cmd/run_pipeline.go:241 +0x89b
github.com/loft-sh/devspace/cmd.NewDevCmd.func1(0xc00089a308?, {0x46d29e0?, 0x4?, 0x25f37a3?})
        /Users/runner/work/devspace/devspace/cmd/dev.go:32 +0x45
github.com/spf13/cobra.(*Command).execute(0xc00089a308, {0x46d29e0, 0x0, 0x0})
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a5508)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/work/devspace/devspace/vendor/github.com/spf13/cobra/command.go:992
github.com/loft-sh/devspace/cmd.Execute()
        /Users/runner/work/devspace/devspace/cmd/root.go:151 +0x1be
main.main()
        /Users/runner/work/devspace/devspace/main.go:17 +0x2a
```

This error is not reproduced in other O/S such as Debian Bookworm, Ubuntt Focal Lossa, Jammy, macOS 15.0.1. reinstalling devspace does not resolve this issue(it was ok in devcontainer with `mcr.microsoft.com/devcontainers/php:7.4-bullseye` image so far. 

**What did you expect to happen instead?**  
I've expected to run `devspace dev` without exception.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My devspace.yaml:
```
version: v2beta1
name: blackcircles2021
vars:
    IDEKEY:
        question: "xdebug.idekey: "
        default: "develop"
# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
    # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
    dev:
        run: |-
            run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
            ensure_pull_secrets --all    # 2. Ensure pull secrets
            create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
            start_dev app                # 4. Start dev mode "app" (see "dev" section)
    # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
    deploy:
        run: |-
            run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
            ensure_pull_secrets --all                         # 2. Ensure pull secrets
            build_images --all -t $(git describe --always)    # 3. Build, tag (git commit hash) and push all images (see "images")
            create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
    app:
        image: my-image-registry.tld/username/app
        dockerfile: ./Dockerfile
# This is a list of `deployments` that DevSpace can create for this project
deployments:
    app:
        # This deployment uses `helm` but you can also define `kubectl` deployments or kustomizations
        helm:
            # We are deploying this project with the Helm chart you provided
            chart:
                name: component-chart
                repo: https://charts.devspace.sh
            # Under `values` we can define the values for this Helm chart used during `helm install/upgrade`
            # You may also use `valuesFiles` to load values from files, e.g. valuesFiles: ["values.yaml"]
            values:
                containers:
                    - image: my-image-registry.tld/username/app
                service:
                    ports:
                        - port: 8080

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
    app:
        # Search for the container that runs this image
        imageSelector: my-image-registry.tld/username/app
        # Replace the container image with this dev-optimized image (allows to skip image building during development)
        devImage: ghcr.io/loft-sh/devspace-containers/php:7-fpm
        # Sync files between the local filesystem and the development container
        sync:
            - path: ./
        # Open a terminal and use the following command to start it
        terminal:
            command: |
                sed -i -e 's/\r$//' .devcontainer/devspace/devspace_start.sh
                .devcontainer/devspace/devspace_start.sh
        # Inject a lightweight SSH server into the container (so your IDE can connect to the remote dev env)
        ssh:
            enabled: true
        # Make the following commands from my local machine available inside the dev container
        proxyCommands:
            - command: devspace
            - command: kubectl
            - command: helm
            - gitCredentials: true
        # Forward the following ports to be able access your application via localhost
        ports:
            - port: "8080"
        reversePorts:
            - port: "9003" # XDebug Port
        # Open the following URLs once they return an HTTP status code other than 502 or 503
        open:
            - url: http://localhost:8080

# Use the `commands` section to define repeatable dev workflows for this project
commands:
    migrate-db:
        command: |-
            echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
            echo 'Anyone using this project can invoke it via "devspace run migrate-db"'
...
```

**Local Environment:**  
- DevSpace Version: 6.3.15
- Operating System: Windows 11 Pro Education 26100.3775
- ARCH of the OS: AMD64 
**Kubernetes Cluster:**  
- Cloud Provider: bare-metal k3s
- Kubernetes Version: Kustomize Version: `v5.5.0` | Server Version: `v1.31.3+k3s1`

**Anything else we need to know?**
