### ISSUE TITLE
Default for question vars is "<nil>"

### ISSUE THREAD

**Issue by jackwilsdon** [devspace-sh/devspace#2971]
**What happened?**  
The default value for question vars is "<nil>". This causes issues when trying to make a variable required using `validationPattern` (see attached `devspace.yaml`).

**What did you expect to happen instead?**  
The default value to be an empty string.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. `devspace deploy` the attached `devspace.yaml`

My devspace.yaml:
```
version: v2beta1
vars:
  EXAMPLE:
    question: Example
    validationPattern: .+
    validationMessage: An access token is required
```

The workaround is to also set `default: ""`. Interestingly enough, password variables (`password: true`) do default to an empty string from what I can tell.

**Local Environment:**  
- DevSpace Version: [use `devspace --version`] 6.3.15
- Operating System: macOS
- ARCH of the OS: ARM64
