### ISSUE TITLE
DevSpace should print an error if profile configuration is invalid

### ISSUE THREAD

**Issue by jmarbach** [devspace-sh/devspace#888]
I am trying to configure my Rails application for deployment in both the development and production environments, however, I am not able to successfully deploy Rails in production.

**What happened?**

I configured a profile patch to replace the env variable `RAILS_ENV`:

```
version: v1beta6
images:
  default:
    image: dscr.io/${DEVSPACE_USERNAME}/modernpricing
deployments:
- name: modernpricing
  helm:
    componentChart: true
    values:
      containers:
      - image: dscr.io/${DEVSPACE_USERNAME}/modernpricing
        env:
          - name: RAILS_ENV
            value: "development"
      service:
        ports:
        - port: 3000
dev:
  ports:
  - imageName: default
    forward:
    - port: 3000
  open:
  - url: http://localhost:3000
  sync:
  - imageName: default
    excludePaths:
    - devspace.yaml

profiles:
- name: production
  patches:
  - op: replace
    path: deployments[0].helm.values.containers[0].env
    env:
    - name: RAILS_ENV
      value: "production"
```

I then ran `devspace dev -b -p production`

Requests to the root, `localhost:3000` returned an error:

```
[modernpricing] [2020-01-21 04:16:08] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03Yx\bz\x06�`Km&|p#��,���~�� |����n��� jxc�5\x12�\x01\x0F\a\x01����ߗ�<\x01?r\x1D��H\x1Ei�\x0F\x00�\x00"��\x13\x01\x13\x02\x13\x03�+�/�,�0̨̩�\x13�\x14\x00�\x00�\x00/\x005\x00'.
[modernpricing] 127.0.0.1 - - [21/Jan/2020:04:16:08 UTC] "\x16\x03\x01\x02\x00\x01
```

When I run `devspace enter - rails c` to access the Rails console, I get an error:

```
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"-\": executable file not found in $PATH": unknown
```

**What did you expect to happen instead?**

I expected requests to the app's root, e.g. `localhost:3000`, to render the index view.

**How can we reproduce the bug?** (as minimally and precisely as possible)

1. Create a new Rails application
2. Create a config profile with a patch that changes the environment variable `RAILS_ENV`
3. Deploy the Rails application using the production config profile
4. Request a valid route in your app

**Local Environment:**

* Operating System: mac
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: DigitalOcean
* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Notes**

* I disabled forced SSL in my config/production.rb file, `config.force_ssl = false`

/kind bug

**Comment by FabianKramm** [comment]
@jmarbach thanks for opening this issue! There is a problem in the configuration at 

```
...
patches:
  - op: replace
    path: deployments[0].helm.values.containers[0].env
    env:
    - name: RAILS_ENV
      value: "production"
...
```

this should look like

```
...
patches:
  - op: replace
    path: deployments[0].helm.values.containers[0].env
    value:
    - name: RAILS_ENV
      value: "production"
...
```

then it will work. So it is actually not really a bug, however we should improve the profile validation, because DevSpace should print an error in this case that the configuration is invalid.
