### ISSUE TITLE
Skipped building image when docker image is missing

### ISSUE THREAD

**Issue by igoooor** [devspace-sh/devspace#941]
**What happened?**
I started my local config with `devspace dev --config=some-path/devspace.yaml` and it build and deployed everything successfully.
I then stopped my deployment `devspace purge --config=some-path/devspace.yaml`, I manually deleted the created docker images `docker image rm ...`.
Then I wanted to restart my application with `devspace dev --config=some-path/devspace.yaml` and this time it skipped the building of the images and only deployed:

```
[info]   Skip building image 'app-nginx'                                        
[info]   Skip building image 'app-php'
[done] √ Deployed helm chart (Release revision: 0)                
[done] √ Successfully deployed website with helm  
```

But if I check my pods, they are in Status **ImagePullBackOff** as the docker images are missing.
I tried to `devspace cleanup images --config=some-path/devspace.yaml` but it does not make a difference.
The only way to make my setup working again is to rename my images:
from:

```
images:
  app-php:
    image: app/php
    tag: latest
    ...
  app-nginx:
    image: app/nginx
    tag: latest
```

to:

```
images:
  newname-php:
    image: app/php
    tag: latest
    ...
  newname-nginx:
    image: app/nginx
    tag: latest
```

Am I missing something? It should at least check that the docker image still exists no?

**Local Environment:**

* Operating System: mac
* Deployment method: helm
* devspace version 4.5.0

**Kubernetes Cluster:**

* Cloud Provider: local with docker for mac
* Kubernetes Version: 1.16

/kind bug
