### ISSUE TITLE
Unable to devspace build without --build-sequential option

### ISSUE THREAD

**Issue by zadigus** [devspace-sh/devspace#997]
**What happened?**
If I run

```
devspace build
```

then it takes forever until I have some build. Actually, I've not had enough patience yet to wait until it finishes (the maximum I've been waiting so far is 36 minutes). If I, however, run

```
devspace build --build-sequential
```

then the images get build within 20 minutes.

I tried both commands after

```
devspace cleanup images && docker system prune -af
```

in order to make sure I have the same setup each time. I am using docker builds, like e.g.

```
images:
  api:
    image: shopozor/graphql-engine
    tag: ${DEVSPACE_RANDOM}
    dockerfile: Dockerfile
    context: .
    build:
      docker:
        options:
          target: hasura-migrations
```

I have a monorepo where I build several micro-services.

**What did you expect to happen instead?**
Because `--build-sequential` means to me that probably the default is some kind of parallel build, I'd expect that

* the build be faster without option `--build-sequential`
* the build be possible without option `--build-sequential`

**How can we reproduce the bug?** (as minimally and precisely as possible)
I can only give my own configuration. I haven't tried to use the devspace setup on some kind of boilerplate monorepo. Here's my configuration: [https://github.com/shopozor/services](https://github.com/shopozor/services), on the `dev` branch. My monorepo contains several services whose docker images are built according to the only `Dockerfile` I have at its root.

**Local Environment:**

* DevSpace Version: 4.6.0
* Operating System: windows
* Deployment method: helm

**Kubernetes Cluster:**

* Cloud Provider: docker for desktop
* Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019
```

Would that be any better with kaniko? Is there something wrong with my `Dockerfile`?

/kind bug

**Comment by zadigus** [comment]
@FabianKramm I've tried several things with kaniko. Here's an example image I'd like to build:
```
images:
  admin-storybook:
    image: shopozor/admin-storybook
    tags:
    - ${DEVSPACE_RANDOM}
    dockerfile: Dockerfile
    context: .
    build:
      kaniko:
        options:
          target: admin-storybook
          buildArgs:
            ASSETS_API: http://assets.shopozor/
```
I've tried to use my local cluster, docker for desktop under Windows, and my remote cluster, hosted on Jelastic. In both cases, if I do a 
```
devspace build --kube-context my-context
```
where `my-context` is set in such a way that I use the docker for desktop or the remote cluster, I get the following error:
```
[fatal]  build images: Error building image shopozor/admin-storybook:VusbjD: Info: Building image 'shopozor/admin-storybook:VusbjD' with engine 'kaniko'
Wait: Waiting for build init container to start
Error: Failed to delete build pod: resource name may not be empty
 Error during image build: Timeout waiting for init container
```
Locally, on the docker for desktop cluster, if I do
```
devspace build --build-sequential --kube-context docker-desktop
```
then, after an eternity (and a lot of build output, but apparently not all the builds), I get the following error
```
[error]  Failed to delete build pod: Delete https://kubernetes.docker.internal:6443/api/v1/namespaces/default/pods/devspace-build-rrmkp: EOF
[fatal]  build images: Error during image build: Error during printling build logs: http2: server sent GOAWAY and closed the connection; LastStreamID=31, ErrCode=NO_ERROR, debug=""
```
